### ISSUE TITLE
material-ui plugin throws error when integrated with grommet.io

### ISSUE THREAD

**Issue by SaloniDesai** [DevExpress/devextreme-reactive#1194]
### Current Behaviour

The gridtable styling goes for a toss when used along with the grommet.io. It throws warning errors such as 
**validateDOMNesting(...): <div> cannot appear as a descendant of <p>.
    in div (created by FlexibleSpace)
    in FlexibleSpace (created by Toolbar)
    in TemplatePlaceholder (created by GroupingPanel)
    in TemplatePlaceholder (created by SearchPanel)
    in TemplatePlaceholder (created by ColumnChooser)
    in TemplatePlaceholder (created by Toolbar)
    in div (created by Toolbar)**

and the table styling looks like:
![screen shot 2018-06-14 at 3 30 42 pm](https://user-images.githubusercontent.com/6766619/41433821-ffc095ea-6fe7-11e8-95b6-48d37a393856.png)

Has anyone come across similar error ? Is the clash between grommet and material-ui expected ?

devextreme-reactive: 1.3.0
react: 16.4.0
browser: chrome
bootstrap: none
react-bootstrap: 0.32.1
material-ui: ^1.0.0-beta.47

**Comment by SergeyAlexeev** [comment]
Hi,

> Is the clash between grommet and material-ui expected ?

Yes it is. If you inspect Grid's markup, you will see that HTML elements contain both Material-UI and Grommet styles. That's why filter editors have unexpected borders, for instance.

Currently, we provide packages only for Bootstrap 3/4 and Material-UI. But it's still possible to use other component suites, like Grommet, with our React Grid.

Let's look at the `TableFilterRow` plugin, for example. As you can see in [documentation](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-filter-row/), you can import the themeless plugin from the `@devexpress/dx-react-grid` package. This package doesn't contain any UI elements, just abstract components. Next, implement plugin components such as a row, a cell, a filter editor etc.

I've created a [sample](https://codesandbox.io/s/38rw02zoy6) that shows how to build a custom TableFilterRow plugin using Grommet. I've used Grommet only for a table filter row. The `Table` and `TableHeaderRow` plugins are imported from the `dx-react-grid-material-ui` package. You can see how we use this approach in our [source code](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-material-ui/src/plugins/table-filter-row.jsx).

As for the `validateDOMNesting(...)` exception, it's quite difficult to understand what is going wrong without your code. Well, it would be great if you provide us with a small example that demonstrates the issue.
