### ISSUE TITLE
[Bug] VirtualTable iOS Safari twitching while scrolling

### ISSUE THREAD

**Issue by freund17** [DevExpress/devextreme-reactive#1221]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour

While scrolling a VirtualTable on an iOS-Device using Safari, the table-content and -header are noticably twitching.

### Expected Behaviour

No twitching while scrolling. The table-content sticks to the finger.

### Steps to Reproduce (for Bugs)

1. Navigate to the VirtualTable-Demo-Page using iOS Safari: https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/virtual-scrolling/
2. Scroll the VirtualTable

### Environment (mine)

- devextreme-reactive: 1.3.0
- react: 16.4.1
- vue: none
- browser: iOS Safari (iOS 11.4)
- bootstrap: none
- react-bootstrap: none
- <span>@</span>material-ui/core: 1.2.3

**Comment by freund17** [comment]
@kvet were you able to reproduce the bug?

**Comment by kvet** [comment]
Hi,

I've reproduced this behavior and found that it occurs only in iframe. If you run that demo without iframe, the table content will not twitch. The issue is caused by the iframe specificity in Safari (iOS) that we cannot overcome on our side using JavaScript code or CSS rules. Here is a link to the bug in Safari: https://bugs.webkit.org/show_bug.cgi?id=187320
