### ISSUE TITLE
[Question] Dynamic input/toggle components don't work

### ISSUE THREAD

**Issue by franklixuefei** [DevExpress/devextreme-reactive#1338]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

### Current Behaviour
Dynamically changing the input/toggle components of `ColumnChooser` and `SearchPanel` don't work.

### Expected Behaviour

It should work.

### Steps to Reproduce (for Bugs)

Clicking the `click` button should toggle the visibility of the column chooser/search panel components.

https://codesandbox.io/s/98qmw101j4

### Environment

- devextreme-reactive: 1.6.1
- react: 16.4.2
- vue: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: yes

**Comment by kvet** [comment]
Hi.
 
You can't use dynamic components that depend on another component's state this way.

When you pass such a dynamic component, nothing changes for the Grid because the component instance didn't change. As a result, the Grid is not redrawn.

Define components directly or use redux to share the component state. Here is a working example: https://codesandbox.io/s/w6qkkp596k

**Comment by franklixuefei** [comment]
Thanks for the explanation! I searched the issues and this showed up: https://github.com/DevExpress/devextreme-reactive/issues/1201. Seems like this shouldn't have worked, right?

**Comment by kvet** [comment]
In that case it works. This is because the inner Grid state is changed and causes redrawing. In your scenario, the Grid state stays unchanged. We know of that limitation and sometimes provide examples that have less code. But they may not work correctly for any case. We will try to cover generic use cases in all our examples in the future.

**Comment by franklixuefei** [comment]
@kvet Thanks a lot Yury! I finally got it. I believe this is one of the common mistakes React devs would make easily.
