### ISSUE TITLE
Paging and Scroller

### ISSUE THREAD

**Issue by gwmaster** [DevExpress/devextreme-reactive#1386]
Help build scrollbar on Grid when Paging

My sample code:
https://codesandbox.io/s/7k93042990

how its look right now
![image](https://user-images.githubusercontent.com/5362853/45032020-4ae68780-b059-11e8-9344-52d128ee1365.png)

- [* ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...
- [* ] React Grid
- [ ] React Chart
- [ ] Vue Grid

**Comment by MaximKudriavtsev** [comment]
Hi,

To achieve your goal, you should use the `VirtualTable` plugin instead of `Table`. The VirtualTable plugin has property `height` for seting a VirtualTable's height, see [API reference](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/virtual-table/).

In the following [example](https://codesandbox.io/s/3xq9yv98j6) you can see how to achieve this.

Note: for correct operation you should add bootstrap styles to the `head` of your application. And other required libriaries be added as well, see [Getting Started guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/getting-started/).

**Comment by gwmaster** [comment]
Thank you!

**Comment by gwmaster** [comment]
i try build tree on vScroll + PagingPanel as i have performance problems when click on smile to change it when more than 2000 Rows rendered.
this how its look on my pc
![image](https://user-images.githubusercontent.com/5362853/45766235-bf1b5080-bc3f-11e8-8d3a-0066a8cfa580.png)

i build [`example`](https://codesandbox.io/s/82pv3p1pkj)  its have some problem on tree this example the same code as on my local.
the main problem is that i render 10,000 rows on tree and on top level i show only 832 so i expected see 1 page but its show me 7.
