### ISSUE TITLE
Sort problem when use Virtual Tree Table and Paging

### ISSUE THREAD

**Issue by gwmaster** [DevExpress/devextreme-reactive#1415]
sort problem when use 

TreeDataState
PagingPanel
VirtualTable

[demo](https://codesandbox.io/s/lrw1ov0w5l)

go to page 2 to see the rendered data

- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] Vue Grid

**Comment by MaximKudriavtsev** [comment]
Hi,
 
In your case, you should place the `CustomTreeData` plugin over of the `IntegratedPaging` plugin because `IntegratedPaging` uses the "rows" [Getter](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/getter/)  that is changed by the `CustomTreeData` plugin.

The order of integrated and custom plugins can change your Grid's data processing logic. See this [guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/plugin-overview/) for more information.
 
See my [example](https://codesandbox.io/s/v8rr6m1noy) with `TreeDataState`, `PagingPanel`, and `VirtualTable`, which works correctly.
 
I found the following issues in your code:
1. You use both `Table` and `VirtualTable`, which is incorrect.
2. Your example includes many plugins and methods, which makes understanding the code and finding the problem difficult. If you remove the code that does not relate to our grid, we will be able to identify the issue much faster.
3. You do not follow the Best practice when using our React Grid (and any our React products): place `...State` plugins first, then - `Integrated...` and `Custom...` plugins, and at the end - UI plugins.

**Comment by gwmaster** [comment]
ty for you feedback.
i fix my code but as it turned out this don't fix my performance problem the VirtualTable and PagingPanel have same performance when editing the data.
i try use VirtualTable+PagingPanel to render 10,000 rows and edit them as shown in my example of smile.
but this is another problem thank you for you quick response.

**Comment by MaximKudriavtsev** [comment]
Your sample contains a lot of custom code.

Let's try to isolate a problem. I've created a [demo](https://codesandbox.io/s/jp61p7rz95) that contains the functionality you described. Does it work correctly on your side?

**Comment by MaximKudriavtsev** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
