### ISSUE TITLE
grouping header issue

### ISSUE THREAD

**Issue by muhammedesadkaya** [DevExpress/devextreme-reactive#1417]
hi there. i want to use grouping on header but i pushed all my compotents to footer with template and templateplaceholder. so my header is empty now but i want to use grouping compotent on header. help please :)

**Comment by SergeyAlexeev** [comment]
Hi,

In this case, you can place a column chooser button into a Grid footer manually and don't use the 'toolbarContent' template. The point is that the 'toolbarContent' template contains both components - a column chooser button and a grouping panel. In your scenario, it isn't useful, because the grouping panel will be rendered in a grid footer instead of a Grid header.

In this [sample](https://codesandbox.io/s/41qooxjl0) I placed the column chooser button into the 'footer' template. Then, I used it as a target for the column chooser's overlay component.
