### ISSUE TITLE
How to properly use connectProps to pass additional prop to TableFilterRow cellComponent

### ISSUE THREAD

**Issue by jimmycarlinco** [DevExpress/devextreme-reactive#1654]
Hello, I am able to use connectProps to pass props to TableFilterRow cellComponent like this:
`          <TableFilterRow
            showFilterSelector
            cellComponent={connectProps(FilterCellComponent, () => ({ gridType: this.props.gridType }))}
          />
`

The issue I am experiencing with this approach is that whenever I change a filter the input field loses focus after one typed character. I don't exactly understand why this happens and what is the proper way to pass props with connectProps.

I would be grateful if anyone with a greater understanding of connectProps can shed some light on this issue.

Thanks a million if you can help! 👍 

- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

**Comment by DmitryBogomolov** [comment]
Hello.

Calling `connectProps` inside the `render` method (as can be implied from your sample) creates new *CellComponent* on every `render` call. Because of it, the previous cell component is unmounted and the new one is mounted. Most likely this is why an input field loses focus.
You should call `connectProps` outside the `render` method (`constructor` is a suitable place) and call the `update` method every time the `this.props.gridType` property changes.

```javascript
// in constructor
this.cell = connectProps(FilterCellComponent, () => ({ gridType: this.props.gridType }));
...
// in render
<TableFilterRow cellComponent={this.cell} ... />
```
 
Let me know if it helps.

**Comment by jimmycarlinco** [comment]
That helped, one question though: what is the correct lifecycle method to check for the prop change and call update? :)

**Comment by jimmycarlinco** [comment]
Thank you, I think everything is answered, I'm closing the issue.
