### ISSUE TITLE
You cant have an empty column title

### ISSUE THREAD

**Issue by emattias** [DevExpress/devextreme-reactive#1769]
I need to have a header cell that is empty. Because of this line it gets set to the column name: https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid/src/plugins/table-header-row.jsx#L128

The hacky workaround of setting the title to `' '` works for my case but that limits the min-width of the column since its a space character and not actually empty. Just visually empty.

- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

**Comment by ushkal** [comment]
Hi, 

Could you please describe your scenario in greater detail - why do you need a column with an empty title having a width less than a symbol width? It will help us to improve our api.
While such columns are not supported by design, you can use the following workaround: override the TableHeaderRow plugin's titleComponent to provide your own column caption as shown in [this sample](https://codesandbox.io/s/m7zmk4vjn9).
