### ISSUE TITLE
TableFixedColumn: Header stays fixed, column doesn't

### ISSUE THREAD

**Issue by bcmux** [DevExpress/devextreme-reactive#1789]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.
Potentially related to: https://github.com/DevExpress/devextreme-reactive/issues/1489

### I'm using ...
- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
Setting a TableFixedColumn on a column that has custom cells only keeps the column's header cell fixed, and not the remaining cells in the column. TableFixedColumns works on non-custom cells as expected. Adding a unique key to each custom cell in the column doesn't seem to help either.

### Expected Behaviour
The entire column, both header and the column cells, should stay fixed.

### Steps to Reproduce (for Bugs)
https://codesandbox.io/s/w7zlq80kww

### Environment

- @devexpress/dx-react-core: 1.10.0
- @devexpress/dx-react-grid: 1.10.0
- react: 16.7.0
- browser: Chrome 71.0.3578.98
- material-ui: 3.9.0

**Comment by MaximKudriavtsev** [comment]
Hi @bcmux,
 
You forgot to spread all props to your custom component. You can find how to override components in the [Fundamentals Guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/#appearance-customization). I've updated your [example](https://codesandbox.io/s/r4yr0j6zxp).

**Comment by bcmux** [comment]
Oh neat, that works. Thanks! I was following the **Cells** section of the Fundamentals Guide to achieve this setup.

Out of curiosity, how would someone know when to spread all the props to a custom component and when not to?

**Comment by MaximKudriavtsev** [comment]
@bcmux,

Thank you for your feedback. We are going to update our documentation to describe this specificity.

As for your question, our API reference [lists properties](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#interfaces) that a component provides. In case you override a component, for example, the Cell component, we recommend that you check the [API reference](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#tabledatacellprops) in order not to miss any of them. 
 
I suggest that you make the props option available everywhere where it is possible since almost all our components have logic that depends on this option.
 
```jsx
const Cell = ({ value, ...restProps }) => (
  <Table.Cell
    {...restProps} // this should be above always
    value={`${value * 2}`}
    row={/* */} // this property overrides the `restProps`
  />
);
```
 
In case you are using a custom component without our built-in components, making the props option available everywhere is not necessary. 

```jsx
const Cell = ({ value }) => (
  <td
    value={`${value * 2}`}
  />
);
```

**Comment by bcmux** [comment]
Awesome, thanks for the explanation. That makes perfect sense. I'm going to close this now since all my concerns have been addressed. :)
