### ISSUE TITLE
Pager is not found in @devexpress  React-Grid

### ISSUE THREAD

**Issue by NIMISHAMORADIYA** [DevExpress/devextreme-reactive#1837]
i am facing this error at run time.

./node_modules/@devexpress/dx-react-grid-bootstrap3/dist/dx-react-grid-bootstrap3.es.js
Attempted import error: 'Pager' is not exported from 'react-bootstrap'.

Though i m not using pager in my code. Is there any bug from package side?
Please guide me through this.

#react #pagination #datatable

**Comment by SergeyAlexeev** [comment]
Hi,
 
As far as I understand, you are using the latest version of the 'react-bootstrap' library, aren't you? If so, starting with v1.0.0 the 'react-bootstrap' is [switched](https://react-bootstrap.github.io/migrating/) to [Bootstrap v4](https://getbootstrap.com/). We are using an [old](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid-bootstrap3/package.json#L88) version of the 'react-bootstrap' library in our 'dx-react-grid-bootstrap3' package to be compatible with [Bootstrap v3](https://getbootstrap.com/docs/3.4/). If your application is based on Bootstrap v3, you need to downgrade the 'react-bootstrap' library to v0.32.4. Otherwise, if you prefer Bootstrap 4, I suggest you use the [dx-react-grid-bootstrap4](https://www.npmjs.com/package/@devexpress/dx-react-grid-bootstrap4) package.
