### ISSUE TITLE
Change filters columnName to getCellValue columnName

### ISSUE THREAD

**Issue by susuwatari2** [DevExpress/devextreme-reactive#1854]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
In controlled mode, I can filter when the new value in getCellValue and doesn't matter what the filters columnName is.

In the [sample](https://codesandbox.io/s/ko54kw4zv7), it is returning 
    filters:[ { columnName: "cityid", value: "las", operation: "contains" } ]

In remote mode, I cannot filtering the new column value in getCellValue because it is the old columnName.

### Expected Behaviour
If I am using the `getCellValue` on the columns, can I get the new column names passing in the `this.state.filter` ?

In the above sample, would like to return
    filters:[ { columnName: "cityname", value: "las", operation: "contains" } ]

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by SergeyAlexeev** [comment]
Hi,
 
The `getCellValue` function doesn't specify a column name. It gets a cell value from a row. That's why this function doesn't affect the `columnName` field in a filter object.
 
> In remote mode, I cannot filtering the new column value in getCellValue because it is the old columnName.

I'm not sure I understand the problem. If you are using remote filtering, you can create any query string and pass it to the server side. Please take a look at this [sample](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/filtering#remote-filtering).
