### ISSUE TITLE
Vue TypeError: Cannot read property 'offsetHeight' of undefined

### ISSUE THREAD

**Issue by boss225** [DevExpress/devextreme-reactive#1857]
In vuejs, when I switch from one page to another with component table, I get this error. Tell me how to fix it ?
- i use sorting and virtual scrolling in Vue grid
https://devexpress.github.io/devextreme-reactive/@next/vue/grid/docs/guides/sorting/
https://devexpress.github.io/devextreme-reactive/@next/vue/grid/docs/guides/virtual-scrolling/
- code example:
```
<template>
  <div class="table-custom">
    <DxGrid
      :rows="items"
      :columns="fields"
    >
      <DxSortingState 
        :sorting.sync="sorting"
        :columnExtensions="sortingStateColumnExtensions"
      />
      <DxVirtualTable />
      <DxIntegratedSorting />
      <DxTableHeaderRow showSortingControls />
    </DxGrid>
  </div>
</template>
```

**Comment by SergeyAlexeev** [comment]
Hi,
 
We've [fixed](https://github.com/DevExpress/devextreme-reactive/pull/1764/files#diff-362de36c43774b29e728ead42b967adeR88) a similar issue in React Grid. It looks like this trick should solve the problem. Of course, `componentWillUnmount` should be changed to [beforeDestroy](https://vuejs.org/v2/api/#beforeDestroy). Vue Sizer is [here](https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-vue-core/src/sizer.js).

Since we [deprecated](https://devexpress.github.io/devextreme-reactive/vue/grid/docs/guides/getting-started/) our Vue Grid, you can use [DevExtreme Vue Components](https://github.com/DevExpress/devextreme-vue) instead.
