### ISSUE TITLE
Custom Toolbar component makes a column chooser popup go to the top left of the screen

### ISSUE THREAD

**Issue by sometimesElen** [DevExpress/devextreme-reactive#1888]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
In my system, I have a Grid that its content is updated every 10 seconds. The problem happens when the user clicks on the column visibility chooser then the menu popup appears. Until this moment everything goes ok. But then when the grid gets your content update then this menu popup goes to the top left of the screen.

### Expected Behaviour
A column chooser popup menu has to stay at its place.

### Steps to Reproduce
I've created a demo page with the bug:
https://codesandbox.io/s/93r7orowxr?fontsize=14
To reproduce just click on the column chooser button and wait the grid content get updated (max 10 seconds) 

### Screenshots
[Screencast](https://www.dropbox.com/s/pmf64itz7xo4lcs/IxVWOX2kAA.mp4?dl=0)

### Environment

- devextreme-reactive: 1.10.3
- react: 16.8.3
- browser: Google Chrome  72.0.3626.121
- material-ui: 3.9.2

**Comment by SergeyAlexeev** [comment]
I've researched the [sample](https://codesandbox.io/s/93r7orowxr?fontsize=14) and found that  a custom toolbar root component is placed inside a render function. In this case, this component will be created on each grid update. That's why a column chooser loses a target and has a wrong position.

The fix is quite simple - move the custom toolbar root component outside the render function. Take a look at the [updated sample](https://codesandbox.io/s/54m38lvw1x) as well.

**Comment by zhdanouskikh** [comment]
I have the same issue

Everything worked fine for me with uncontrolled TableColumnVisibility component.
But when I switched to controlled one, I have the same issue as you have

Hack with moving toolbar rootComponent function outside of render didn't help me.
I can't reproduce it in sandbox btw :(
