### ISSUE TITLE
Cypress E2E

### ISSUE THREAD

**Issue by cavr** [DevExpress/devextreme-reactive#1907]
Is there an easy way to use Cypress? I am having problems with selectors when testing DataGrid using Cypress?

**Comment by SergeyAlexeev** [comment]
Hi,

Would you please clarify what template suite you are using: Bootstrap 3/4 or Material-UI?

> I am having problems with selectors

I suppose it's Material-UI. If so, I'd like to point that Material-UI components are created based on [JSS](https://cssinjs.org/). That's why html element class names are dynamic:

![image](https://user-images.githubusercontent.com/1897913/54341571-2cd29300-464b-11e9-9f15-9c23cacf749c.png)

I've found the related [issue](https://github.com/cypress-io/cypress/issues/1212) in cypress repo.

Did you try [TestCafe](https://github.com/DevExpress/testcafe) for end-to-end testing? There is a [plugin](https://www.npmjs.com/package/testcafe-react-selectors) that makes it easier to test React components. Moreover, [TestCafé Studio](https://www.devexpress.com/products/testcafestudio/) contains an integrated Visual Test Recorder, which allows you to specify a particular selector for an html element. For example, you can select an element by a class name, tag name or attribute.

**Comment by cavr** [comment]
@SergeyAlexeev 
Yes I'm using Material-UI. 
I will try TestCafe instead because using Cypress is imposible at the moment.
Thanks.
