### ISSUE TITLE
Grid - All rows are re-rendered when editing a row if VirtualTable is used

### ISSUE THREAD

**Issue by artem-kurchenko** [DevExpress/devextreme-reactive#1925]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid

### Current Behaviour
Here are two sandbox demos:
1) https://codesandbox.io/s/w215mo8j6k 
2) https://codesandbox.io/s/vvvx383800  
   https://codesandbox.io/s/k36wqkw62v (Bootstrap 4)

Demo (1) uses the Table component and it only re-renders the edited row when you click save.
Demo (2) uses the VirtualTable component and it re-renders 12 rows on each input change. 

### Expected Behaviour
A single row should be re-rendered on editing if VirtualTable is used

### Environment

- devextreme-reactive: 1.10.4
- react: 16.6

**Comment by SergeyAlexeev** [comment]
**Current progress:**

We researched the problem and found that it doesn't appear if there is no seamless-immutable library. This [sample](https://codesandbox.io/s/o74qrkqzmq) shows it in action.
The seamless-immutable library can be removed from an [initial sample](https://codesandbox.io/s/vvvx383800), because we transform immutable entities into mutable ones, for example: `editingRowIds.asMutable()`.
