### ISSUE TITLE
Customize ColumnChooser

### ISSUE THREAD

**Issue by susuwatari2** [DevExpress/devextreme-reactive#1982]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Is it possible to customize the appearance of the column chooser? 
I want it to separate from one column into two columns.
I also want to create a input box on the top of the column list which filters the columns.

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by ushkal** [comment]
Hi @susuwatari2,
 
I recommend the following: 
1) To show two columns instead of one, override the containerComponent of the [ColumnChooser ](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/column-chooser/#properties)plugin and render your own implementation of the 2-column list or change the layout of the existing list via css as in the case with Material-UI.
2) Add an input component using the overlayComponent.
3) Pass a filter value to the Item component using a React Context.
4) Conditionally render an itemComponent depending on the filter value.

Here is an [example](https://codesandbox.io/s/5xwwpmz40x).

**Comment by susuwatari2** [comment]
Hi @ushkal,
In the ColumnChooser plugin, I use react-bootstrap, with cannot use WithStyle. What is the alternative approach?

**Comment by ushkal** [comment]
You can use css classes or inline styles for this purpose. Here's an [example ](https://codesandbox.io/s/4qzqrmnv69)for Bootstrap 3 theme.

**Comment by susuwatari2** [comment]
I tried with your example with Bootstrap 3. It passed the filter value but it doesn't render any columns on the ColumnChooser.

**Comment by ushkal** [comment]
I've tested the example in Chrome, Edge and Firefox, and it works as expected; see the attached screencast. Would you please illustrate the problem?

![column-chooser](https://user-images.githubusercontent.com/44223690/56720450-88646600-674b-11e9-9d81-121171afba85.gif)

**Comment by susuwatari2** [comment]
It wasn't working in my codesandbox but I am able to create the component. I am not using react 16.8 and useState what is the way to pass filterValue? SetState fires when the column chooser is reopened.

**Comment by susuwatari2** [comment]
Hi @ushkal,
Like your sample, it is case sensitive. How would we fix that?
