### ISSUE TITLE
How to add additional selection column 

### ISSUE THREAD

**Issue by annanouch** [DevExpress/devextreme-reactive#2083]
Hi, I am using React-grid i need to know how to implement two checkbox in Selection here is an image that explains my problem
![image](https://user-images.githubusercontent.com/15823170/59318723-dd3e4a80-8cbf-11e9-8703-d6c81b3aa6fc.png)

**Comment by MaximKudriavtsev** [comment]
Hi @annanouch,

This is a complex scenario and it is necessary to understand the [DevExpress React Core](https://devexpress.github.io/devextreme-reactive/react/core/docs/guides/fundamentals/) concept to achieve it. The `tableColumns` [getter](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/getter/) consists of each column which Grid renders. The main idea is to add a custom selection column and Grid is going to render it. For it, you should create a custom plugin - please see the [Custom Plugin Development](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/) guide for details on how to do it.

The [following demo](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-j5cn2) illustrates the expected behavior.
