### ISSUE TITLE
Set number of ekstra rows to render in VirtualTable

### ISSUE THREAD

**Issue by chr22** [DevExpress/devextreme-reactive#2085]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

In a table with Virtual Scrolling enabled that is both wide and tall with complex rows, gets really bad scrolling performance. I get about 5 FPS in Chrome on a Core i7-8750H CPU which is one of the fastest on the market for laptops.

I can get smooth scrolling by disabling virtual scrolling but then the rendering becomes really slow (tested with 200 rows).

Would it be possible to combine those two by rendering more rows than the visible ones? Maybe twice the visible rows or maybe make it as a setting, so the user will be able to fine tune the performance for the specific use case.

**Comment by ushkal** [comment]
Hi @chr22 ,
 
We don't have plans to expose this variable. Currently, the Grid renders 3 extra rows. By means of experiments, we found out that this it the optimal number of extra rows. It slightly slows down the performance, but at the same time, provides good user experience (blank rows are not shown on scroll). Increasing the number of extra rows will decrease performance because the React will have a bigger virtual DOM. I suggest you profile and optimize rendering of your complex rows.
