### ISSUE TITLE
Hide column after first render

### ISSUE THREAD

**Issue by ccamusso** [DevExpress/devextreme-reactive#2092]
Is possible hide a specific column after first render?

In this example, hide column not work after click event:
https://codesandbox.io/s/devextreme-react-grid-for-material-ui-qh3g9

Carlo

**Comment by ushkal** [comment]
Hi,
 
This is expected behavior: the properties with the 'default' prefix are not meant to be changed because their values are saved into the plugin's internal state after the plugin constructor's execution. 
There are 2 ways to implement your task: 
1) Assign the `defaultHiddenColumnNames` value to the `key` prop of the `TableColumnVisibility` plugin to force its re-rendering
```
<TableColumnVisibility
    key={defaultHiddenColumnNames}
    defaultHiddenColumnNames={defaultHiddenColumnNames}
/>
```
2) Use the controlled mode for column visibility.
