### ISSUE TITLE
Handling on Row click 

### ISSUE THREAD

**Issue by paufar** [DevExpress/devextreme-reactive#2099]
Are there any known conflicts or dependencies for handling a row click? I am following the demo here https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/fundamentals/#rows  but does not seem to be working. Are there any other demos online which i can check with?

**Comment by MaximKudriavtsev** [comment]
Hi @paufar,

Could you clarify what you mean by `...does not seem to be working?` The demo works fine on my side and the code of this demo demonstrates a proper approach to handle row click.

**Comment by paufar** [comment]
Hi, 

Sorry for not being specific, the demo is working it was when i included it in my project that it didn't work. I just noticed now that the reason why the onClick is not working is because there is a conflict with the TableSelection. 

Components commented out for the onClick to work in my project: 
1. <SelectionState
selection={selection}
onSelectionChange={this.changeSelection}
/>


2.  <IntegratedSelection />


3.  <TableSelection showSelectAll highlightRow />

**Comment by MaximKudriavtsev** [comment]
@paufar,

I [reproduced](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-84pwt) this behavior. We will try to fix this.

**Comment by LazyLahtak** [comment]
Hi @paufar,
Let me explain what happens.
When you use the TableSelection with highlightRow or selectByRowClick properties, TableSelection overrides rowComponent from Table on its own.
https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-selection/#properties
You can use cellComponent instead of rowComponent in Table to process the onClick event (see [this example](https://codesandbox.io/embed/devextreme-react-grid-for-material-ui-33y00)).
You can also define rowComponent in TableSelection. However, it's an undocumented approach. If you want to use it with the selectByRowClick option, add the onToggle() call inside the onClick handler like in [this example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-pbr9m).
If neither of this solutions is applicable for your scenario, let us know.

**Comment by LazyLahtak** [comment]
Hi @paufar,

We researched this behavior and found that it's correct. The last [comment](https://github.com/DevExpress/devextreme-reactive/issues/437#issuecomment-504986730) from the [How to use a custom row template when mouse click selection is enabled](https://github.com/DevExpress/devextreme-reactive/issues/437) thread describes why it occurs and demonstrates a possible solution.
