### ISSUE TITLE
Virtual Scroll fails to load all rows

### ISSUE THREAD

**Issue by emjayoh** [DevExpress/devextreme-reactive#2126]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

Using virtual table and pagination (because of the need for it for sticky header), I am loading page 1 of many, with 100 rows per page. Consistently, it will stop rendering rows after scrolling ~70% down. It simply shows blanked out cells for the rows.

### Expected Behaviour

Should just keep rendering rows.

### Steps to Reproduce

1. Render grid with virtual scroll and pagination and 100+ rows.

### Screenshots

![image](https://user-images.githubusercontent.com/5733079/60306146-fe27b200-98f3-11e9-9db2-27394200f8ea.png)

### Environment

- devextreme-reactive: 1.11.1
- react: 16.7.0
- browser: Chrome (latest)
- bootstrap: none
- react-bootstrap: none
- material-ui: 3.9.0

**Comment by ushkal** [comment]
Hi,

Currently, dx-react-grid doesn't fully support combination of Virtual Table and Paging. I suggest you use the approach illustrated in the "[Remote Paging](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/paging/#remote-paging)" demo. Here's a [modified example ](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-iro9c)with Virtual Table.

**Comment by emjayoh** [comment]
If I do this I cannot have a sticky header, which is the whole reason I'm using Virtual Table.

**Comment by ushkal** [comment]
I've created a [sample project](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-hmjck) with the same plugin structure as in your code and it works as expected. However, I couldn't test your custom 'pullNowButton' plugin because your code lacks some custom components' implementation. Please provide us with a runnable project where the problem is reproduced so that we could find the cause. 
I also recommend you specify the [getRowId](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/grid/#properties) function for selection to work properly across all pages.
