### ISSUE TITLE
What's the best practice for create custom columns?

### ISSUE THREAD

**Issue by madebymt** [DevExpress/devextreme-reactive#2138]
- devextreme-reactive: 1.11
- react-grid
- browser: Chrome
- material-ui:3.9

I'm curious what's the best way to create my own custom columns for react-grid, working on some application, and checking the doc to implement the solution, here's my demo:
https://codesandbox.io/s/devextreme-react-grid-for-material-ui-mhsez?fontsize=14

<img width="729" alt="Screen Shot 2019-07-03 at 8 59 05 PM" src="https://user-images.githubusercontent.com/26178313/60634693-7fd87d80-9dd5-11e9-8894-2ea462ed57a4.png">
)
But I feel like application is a little running slow, so would like to check with an expert to see if I doing the correct way. 
Thank you!

**Comment by ushkal** [comment]
Hi,
 
Your approach is correct. However I suggest you render the default cell's content directly in a cell without a span if it's possible. Also, handle the children property so that the functionality like data formatting properly operates. Here's cell code:
```
...
} else {
      return (
        <Table.Cell {...restProps}>
          {children || value}
        </Table.Cell>
      );
    }
```
 
> But I feel like application is a little running slow
 
I profiled your app with a larger data set and haven't found any performance degradation as compared to a version without a custom column. Make sure you deploy a production version of the application.
