### ISSUE TITLE
Events created on Sunday disappears when firstDayOfWeek is Sunday

### ISSUE THREAD

**Issue by AngelineLim** [DevExpress/devextreme-reactive#2152]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Current Behaviour

When updating firstDayOfWeek props of WeekView from 0 to 1 (Sunday to Monday), event data on Sunday does not appear in view. Please refer to demo [here](https://codesandbox.io/embed/devextreme-react-scheduler-for-material-ui-k3j6t)

### Expected Behaviour

When updating firstDayOfWeek props, event data on Sunday should persist. 

### Steps to Reproduce

1. Use props of firstDayOfWeek:
```
<WeekView 
  firstDayOfWeek={0}
/>
```

### Screenshots

N/A

### Environment

- devextreme-reactive: 1.11.1
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by AryamnovEugeniy** [comment]
Hello @AngelineLim,
 
I updated your [example](https://codesandbox.io/embed/devextreme-react-scheduler-for-material-ui-pryvx) (set firstDayOfWeek to 1 and added AllDayPanel), and event data on Sunday does persist here. Could you please elaborate on the problem with event data on Sunday? The issue is not quite clear to us right now.
