### ISSUE TITLE
GreaterThenOrEqual icon is not found 

### ISSUE THREAD

**Issue by franciscailleAstus** [DevExpress/devextreme-reactive#2213]
- [ X ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

The icon of "GreaterThenOrEqual" doesn't seem to be the good one.

### Expected Behaviour

Icon should be ≥

### Screenshots

![image](https://user-images.githubusercontent.com/44379473/62305095-3ec39f80-b44d-11e9-9730-8b3b7c903809.png)

Also, definition seems to have a typo:
![image](https://user-images.githubusercontent.com/44379473/62305662-5f402980-b44e-11e9-821e-ce2f50065039.png)

### Environment
- dx-react-grid: 2.0.1
- react: 16.8.6
- browser: chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.2.0

**Comment by ushkal** [comment]
Hi @franciscailleAstus ,
 
Would you please clarify where this issue is reproduced? I've examined our [demos](https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/integrated-data-shaping/) and [docs](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/filtering/), but the proper icon is displayed.

![image](https://user-images.githubusercontent.com/44223690/62306030-bdd6c900-b489-11e9-85e8-d85a172972ed.png)

>Also, definition seems to have a typo

We'll fix the typo in the definition file, thank you.

**Comment by franciscailleAstus** [comment]
Oh, I found the issue. I had a miss spell in the name of the operation. My bad.

**Comment by ushkal** [comment]
I am happy to hear that the problem is resolved. Feel free to contact us in case of any difficulty.
