### ISSUE TITLE
What difference between table and virtual table?

### ISSUE THREAD

**Issue by iposokhin** [DevExpress/devextreme-reactive#2241]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
What difference between table component and virtual table component? What has advantages virtual table? Does virtual table has higher performance? Does it use virtualize features like react-window? What features to consider on using virtual table?

### Environment

- devextreme-reactive: 1.10.1
- react: any
- browser: any

**Comment by hammenm** [comment]
You can find the advantages of `VirtualTable` at this link: https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/virtual-scrolling/

> The VirtualTable plugin provides the virtual scrolling mode as an alternative to data paging. It allows end users to navigate to data rows using the vertical scrollbar. In this demo, the Grid with enabled virtual scrolling is bound to a 200,000 record data source.

**Comment by iposokhin** [comment]
Is that all? But performance? What about performance, virtualize?

**Comment by LazyLahtak** [comment]
Hi @iposokhin,

The Table renders all rows, while the Virtual Table renders only visible rows. Thus, the Virtual Table has higher performance. It also allows using remote data instead of local and has a fixed header and footer.
If you prefer scrolling instead paging or need to display a large amount of data, use the Virtual Table.
If you still have questions, please let us know.
