### ISSUE TITLE
The latest version not support Material-UI version 3.9.3?

### ISSUE THREAD

**Issue by shangdev** [DevExpress/devextreme-reactive#2260]
My material-ui version is v3.9.3, unfortunately, when I installed the latest version of devextreme-reactive, he throw error info: theme.spacing is not a function.

So, is there any historical version that can support material-ui v3.9.3?

**Comment by ushkal** [comment]
Hi,
Version 1.11.1 is the latest version of DevExtreme Reactive Components that supports Material-UI 3.

**Comment by MaximKudriavtsev** [comment]
We received many [requests from our customers](https://github.com/DevExpress/devextreme-reactive/issues/2013) and now the DevExtreme Reactive Component [supports Material-UI v4](https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md#200-2019-07-08).

We recommend updating to Material-UI v4 and using the latest versions of our components since new features will only be included in the newest versions.

Also, our previous versions are available on NPM. If you are using Material-UI under v4, you can download version 1.11.1 of the DevExtreme Reactive. For example:

`npm install @devexpress/dx-react-grid@1.11.1`
