### ISSUE TITLE
In Safari a header scrolls out of view in Virtual Table if height is set to auto

### ISSUE THREAD

**Issue by shangdev** [DevExpress/devextreme-reactive#2262]
### I'm using ...

- [ ] React Grid

### Current Behaviour
When I set height="auto" in VirtualTable plugin. unable to work correct in Mobile.
This is demo: [demo](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-hpigw?fontsize=14)

He works correctly on the PC. In mobile, The fixed header will slide up with the content, position: sticky no longer works.

If necessary, I will make a gif. Thanks.

### Environment
- devextreme-reactive: 1.11.1
- react: 16.8.0 +
- browser: ios (mobile) chrome
- material-ui: 3.9.3

**Comment by ushkal** [comment]
Hi,

I've reproduced the issue. We'll fix it soon. As a workaround you can use the react-virtualized's `AutoSizer `component. Here's a modified [project](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-3bv2m).

**Comment by ushkal** [comment]
We've fixed this problem in the scope of issue #2084 . Version [2.0.2](https://github.com/DevExpress/devextreme-reactive/releases/tag/v2.0.2) is already provided with the fix.

**Comment by MaximKudriavtsev** [comment]
Hi @shangdev,

We have published the [1.11.2 version](https://github.com/DevExpress/devextreme-reactive/blob/v1.x/CHANGELOG.md#1112-2019-08-23) of the DevExtreme Reactive components with a fix for this problem.

If you are using the Material-UI v3.x, you can download our package with the following command

```
npm install @devexpress/dx-react-grid@previous_v1
```

We recommend updating to Material-UI v4 and using the latest versions of our components since new features will only be included in the newest versions.
