### ISSUE TITLE
Inline Cell Editing for Reactive Grid

### ISSUE THREAD

**Issue by LazyLahtak** [DevExpress/devextreme-reactive#2284]
# The Problem

Users cannot edit a single table cell by click.

# The Proposed Solution

We plan to add a new plugin that implements an Excel-like editing mode in which users can edit data cell by cell. Edits will be committed once the cell loses focus or when a user presses the Enter key. You will be able to customize editors using the plugin's properties or the `DataTypeProvider` plugin.

![ea368165-1879-4f3f-817d-6469894835b6_waifu2x_photo_noise2_tta_1](https://user-images.githubusercontent.com/43685423/63949853-ad633f80-ca83-11e9-8518-c5b131ed3856.png)

# We Need Your Feedback

## Take a Quick Poll

[Do you find inline cell editing in Reactive Grid useful?](https://docs.google.com/forms/d/e/1FAIpQLSeLFAJrLMrk_MRaAjQyyaPpIpNiBnAtEdNeoTNk0mu_3AyDvw/viewform)

# Get Notified of Updates

Subscribe to this thread or to our [Facebook](https://www.facebook.com/DevExpress.DevExtreme/) and [Twitter](https://twitter.com/devextreme) accounts for updates on this topic.

**Comment by tmaiaroto** [comment]
In addition to losing focus or pressing enter, it would be nice to have an option for timeout. If we could optionally configure it to save after a few seconds since the user last typed something, then the user wouldn't need to do anything. There may be times where the user doesn't change focus from the field and they don't intuitively know to press enter.

This would be a great feature as it's a common need for us and I was going look into adding something like this next while I'm evaluating the component (which is really awesome by the way -- loving it).

**Comment by LazyLahtak** [comment]
Hi @tmaiaroto,
 
Thank you for your response. We don't plan to realize built-in saving of a cell value on timeout, but you can implement it by yourself. Here is an [example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-m2ip3) showing how to do this for TableEditRow, and you can use it for Inline Cell Editing as well.

**Comment by LazyLahtak** [comment]
Hi

We're happy to announce a new TableInlineCellEditing plugin for inline cell editing. Refer to our [docs](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-inline-cell-editing/) to explore its functionality.
Also, we have added new demos about this feature: [React Grid - Inline Cell Editing](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/editing/#inline-cell-editing).
