### ISSUE TITLE
MUI popover menu doesn't work correctly when it's not implemented as separate component inside a grid cell component

### ISSUE THREAD

**Issue by ImKcat** [DevExpress/devextreme-reactive#2426]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

Menu display in the unexpected position

### Expected Behaviour

Menu display in the expected position

### Steps to Reproduce

https://codesandbox.io/s/devextreme-react-grid-for-material-ui-c0lku

**Comment by AryamnovEugeniy** [comment]
Hi,

You can change either `headerCellComponent` `TableCell`'s `paddingLeft` or `IconButton`'s `marginLeft` style property.

If you have further questions, don't hesitate to ask them.

**Comment by ImKcat** [comment]
@AryamnovEugeniy Sorry about the unclear description, I mean that click the menu icon button, the `Menu` will pop up in the incorrect position.

**Comment by AryamnovEugeniy** [comment]
Hi,

We recommend you to create a separate component (outside of render method) to implement the functionality you need (in your case this is TableCell) because it may lead to unexpected behaviour. [Here](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-0x5qb) is a working example.
Also, see [this issue](https://github.com/mui-org/material-ui/issues/12309#issuecomment-408594249) which explains why it may happen.

**Comment by ImKcat** [comment]
@AryamnovEugeniy Thanks a lot

**Comment by AryamnovEugeniy** [comment]
I'm glad that it helped!
