### ISSUE TITLE
React Grid with feature enable disable has issues

### ISSUE THREAD

**Issue by sjsingh85** [DevExpress/devextreme-reactive#2460]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
Link to the example that reproduces the issue: &lt;https://codesandbox.io/s/devextreme-react-grid-for-material-ui-78y30&gt;

I am trying to create a demo of your React Grid control with capability of turning features on and off. Please see the link mentioned above.

1. When Column Resizing button is turned off, the user still see's the resizing option in the headers, and when the user tries to resize a column, a warning is raised in console - "Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method." How can I fix this?

2(A) When the paging is turned off, the paging row at the bottom is removed as expected, but the records in the grid do not update. Is there an event I can raise to update the data in the grid?
2(B) On fresh page, when paging is turned off, and user clicks on any header to sort columns, a row is automatically selected. Can you help me find out why?

3. The overall performance of the page is not coming out that good. I tried using React.memo for individual component containers I have created but of not much help. I even tried VirtualTable component but it made things worse. Looks like there is some kind of memory leak after user toggles a few features but I have not been able to figure that out. 

4. As you can see I have created a wrapper component - customgridroot to always have the grid within the viewport and horizontal scrollbar usable for users. Is this kind of feature already available in the control that I was not able to see in documentation or I will have to create my own workaround like this? 

5. Is there a feature which allows footer/pager bar to be always aligned at bottom of container as with headers when using VirtualTable?

### Environment
- devextreme-reactive: latest
- react: latest
- browser: chrome
- material-ui: latest

Sorry for a long post.
Thanks!

**Comment by MaximKudriavtsev** [comment]
Hi @sjsingh85,

Thank you for your interest in our product and providing an example.

To `enable/disable` Grid features, we recommend using the [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/) and manually resetting state properties to default values instead of conditional rendering plugins.

However, your approach is also available, but you should not use any container components to combine Grid's plugins. Under the hood, we are using the React context and any other custom components can break our flow. This may work more slowly because React should update big parts of DOM. I have updated [your demo](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-rioqp) and now it works as expected. Please take a look at it and let me know your results.
