### ISSUE TITLE
Emptry string as valid unit on table column resizing computation

### ISSUE THREAD

**Issue by xZliman** [DevExpress/devextreme-reactive#2517]
Hi!

- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

On [computed.ts](https://github.com/DevExpress/devextreme-reactive/blob/425917f3ffc634be33e17993b2b99f8fcc16396a/packages/dx-grid-core/src/plugins/table-column-resizing/computeds.ts#L5)

on `line 5` we got:

`const VALID_UNITS = ['px', '%', 'em', 'rem', 'vm', 'vh', 'vmin', 'vmax', ''];`

an empty string `''`

While this is not a valid unit, is there a reason why this is implemented?

It throws an error though for not being valid

### Environment

- devextreme-reactive: 2.1.2
- react: 16.8.6
- browser: Chrome 78.0.3904.70
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.5.0

Thank you!

**Comment by LazyLahtak** [comment]
Hi @xZliman,

These are valid measurement units. The unit `''` doesn't mean that it is possible to use an empty string. This means that we allow the use of a number as a string. For example, 100 equals '100' and they equal '100px'. Here is an [expamle](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-7b3bq) illustrating this.
What behavior do you expect to see if you set `width: '100'` instead of `width: 100`?

**Comment by xZliman** [comment]
Hi @LazyLahtak 

Thank you for your reply,

> What behavior do you expect to see if you set width: '100' instead of width: 100?

I would expect the same behaviour. 

I looked at your example and it makes sense now.

Thanks!

**Comment by LazyLahtak** [comment]
@xZliman 

You are welcome!
