### ISSUE TITLE
Display "End of Results" at the bottom when all records are loaded

### ISSUE THREAD

**Issue by ryanwlaw** [DevExpress/devextreme-reactive#2562]
### I'm using ...

- [ X] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
Is there a feature where a message such as "End of Results" will be displayed at the bottom of the table when the last record is reached?

**Comment by AryamnovEugeniy** [comment]
Hello,

Could you describe this feature in more detail? What specifically do you want to achieve? It would be best if you provided a screenshot of what you want to accomplish.

**Comment by ryanwlaw** [comment]
Hi, basically I would like the user to know that they have reached the last record in the data grid and no more records are to be loaded in. Ex. Once a user has scrolled through all 100 records, I want to display the message "End of Results" right below the 100th record. Thanks!

**Comment by AryamnovEugeniy** [comment]
In this case you can create a plugin ([here](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/) is our guide on how to make one) which will add a new row to `rows` [Getter](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/getter/). Then, you will have to find this row in Table's [rowComponent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#tabledatarowprops) and display it.
Here is an [example](https://codesandbox.io/s/zen-ride-z7ek8) of how to achieve this. Does this solution suit you?

**Comment by ryanwlaw** [comment]
Hi,
Yes, the solution applies to what I need. In addition, I would need this to work with the IntegratedSorting and IntegratedFiltering. i.e. Currently, when applying <IntegratedSorting />, the End of Results message is currently at the top of the log. Any ideas on a clever way to remove the End of Results and reappend the message after onSortChange?

**Comment by AryamnovEugeniy** [comment]
Hello,

Here is an [example](https://codesandbox.io/s/quizzical-violet-clf50) where "End of Results" is always the last row even with Sorting and Filtering plugins. Don't forget that [plugin order](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/plugin-overview/#plugin-order) matters. Plugins are applied in the same order they are defined in the Grid. And if I define `IntegratedEndOfResults` before `IntegratedSorting` it may work incorrectly. And `IntegratedEndOfResults` should be the last of the plugins that modify 'rows' `Getter` so that it would be able to add the last row after all other plugins have already done their job.
If you have any other questions, don't hesitate to contact us.

**Comment by ryanwlaw** [comment]
Ahh..got it. Thanks for the help!
