### ISSUE TITLE
Group header not rendering full width

### ISSUE THREAD

**Issue by jfcernel** [DevExpress/devextreme-reactive#2642]
- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour
The grouped header does not extend all the way to the end of the grid.

### Expected Behaviour
I am expecting the grouped header to extend all the way to the end of the grid like the actual rows do below.

### Steps to Reproduce
I'm not positive on how to reproduce it, but here is the code that I'm using to render my grid. (Sorry the format is a little wonky, it was not cooperating.

`
<Grid rootComponent={this.Root}
 rows={st.data.rows}
columns={st.data.columns}>`

`
<PagingState
 defaultCurrentPage={0}
 pageSize={50}/>`

`<DragDropProvider/>`
 `<SortingState
 defaultSorting={[{columnName: "scheduledDate", direction: 'asc'}]}/>`

`<IntegratedSorting
columnExtensions={integratedSortingColumnExtensions} />`

`<GroupingState
grouping={st.groupingColumns}
onGroupingChange={this.changeGrouping} />`

`<IntegratedGrouping/>`
`<IntegratedPaging/>`

`<VirtualTable
 cellComponent={this.CellContent}
height={'auto'}/>`

`<PagingPanel/>
<TableHeaderRow showSortingControls/>`

`<TableGroupRow
contentComponent={this.Content}
 showColumnsWhenGrouped={true}  />`
`<SelectionState  selection={this.state.selectedRows}
onSelectionChange={this.changeSelection.bind(this)}/>`
`<TableSelection/>`
`{this.ItemCounter()}`
`<Toolbar/>`
`<GroupingPanel/>`
`</Grid>`

### Screenshots

![image](https://user-images.githubusercontent.com/25107516/72582474-e70cd980-38b0-11ea-8d9e-667e21971866.png)

### Environment

- devextreme-reactive: 19.1.5
- react: 16.7.0
- browser: Chrome
- bootstrap: 4.2.1
- react-bootstrap: none
- material-ui: none

**Comment by AryamnovEugeniy** [comment]
Hello,

We couldn't reproduce your issue. Please provide a working example where the issue is reproduced (for instance, in CodeSandbox) or the full code, or at least your imports and custom components so that we can assist you faster.

Also, judging by the docs, the order of your plugins is incorrect (see: [the 'TableGroupRow' plugin requires 'TableSelection' to be defined before it](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-group-row/#dependencies)). We strongly recommend placing `State` plugins before all other plugins. After that, place the `Integrated` plugins and then the `Table` or the `VirtualTable` plugin. Finally, place the `view` plugins, such as `TableGroupRow`.

One more point: the devextreme-reactive version that you stated is not valid because the latest version is 2.4.0. Possibly, you stated the [DevExtreme version](https://js.devexpress.com/), but our version is different. Please, make sure that you are using the latest version of our components.

**Comment by jfcernel** [comment]
The issue ended up being that the <SelectionState> and <TableSelection> needed to be declared before the <TableGroupRow>.  That solves my issue and everything is now rendering properly.  

Thank you very much for the help!
