### ISSUE TITLE
Grouping Cell backgroundcolor

### ISSUE THREAD

**Issue by bakaa99** [DevExpress/devextreme-reactive#2645]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

The background color of group header cell is derived from `theme.palette.background.paper`
shouldn't it be from the `theme.palette.primary.light` like the rest of the theme.

In my case the paper color is `#fff` but the rest of the theme is blue.

### Screenshots

![Screen Shot 2020-01-18 at 8 13 58 PM](https://user-images.githubusercontent.com/36468406/72665560-8061fa00-3a2f-11ea-8583-630a4df4511a.png)

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: xxx

**Comment by ushkal** [comment]
Hi @bakaa99 ,

Other Grid components are transparent so the Paper is visible underneath. That's why the Paper's background color is used for sticky elements such as Group Cell. I suggest you set the background.paper color or override the TableGroupRow's contanerComponent providing the desired color.
