### ISSUE TITLE
Feedback and Usecases: really good job guys!

### ISSUE THREAD

**Issue by terndrup** [DevExpress/devextreme-reactive#265]
Hey all,

I just wanted to let you guys know that you're doing a great job with the DevExtreme react grid and I'm really looking forward to the upcoming components!

At my work I build webapplications for monitoring and interacting with industrial equipment and in late 2016 we started moving all of our applications to ReactJS which sadly meant: no Devexpress. So imagine our hype when you guys announced the CTP of the grid, and we've done some extensive testing already.

There is one use-case that's central to our applications that I'd like to highlight for you guys, and that is live updating the grid or indeed binding it to dynamic/changing data. One of the key advantages of react in my opinion is how good it is at seamlessly updating the DOM and with component states you can really build some powerful real-time data applications. So we will mainly be interested in using the react grid for data that will update on a set relatively frequent interval (i.e. every 15 seconds) after which the grid will need to be redrawn with the new data. Since we're using react, we will likely be using something like Redux to manage the actual fetching, storing and reducing data so the grid will just have its' state updated from the corresponding reducer.

Have you guys done some testing on how the grid handles "live" data and how well it redraws with pagination etc?

Also we are hoping you will be supporting the same awesome filtering, column choosing and grouping functionalities that you have in the DevExtreme grid.

Keep up the awesome work!

**Comment by dxbykov** [comment]
Hi,
 
Thank you for being interested in our React product. 
 
Let me also give you some details regarding live updates. Our Grid renders your application state and applies any state changes in the most efficient way. For instance, if the state hasn't changed, then the Gird does nothing. Otherwise, the Grid re-renders those UI parts that relate to the changed part of the state and React updates the DOM if the resulting rendering differs from the previous one. So, it's all under your control. Update the state in the way you need and be sure the Grid will apply all the changes accordingly. 
 
We will be happy to help you implement the best solution for your application state updates once you need it. Just clarify how much data (how many rows) you are going to pass to the client. Is this data going to be paginated/sorted/filtered/grouped on the client or on the server? How is the client going to be notified about the changes (full data reload via an HTTP GET request, partial data reload via the HTTP GET request, push notifications via WebSockets, etc.)? Should only the currently visible page be updated once a new part of data has come to the client? Should the Grid rows be resorted on the client once some row field has changed and is configured to be the sort row? 
 
Thank you for your collaboration.

**Comment by terndrup** [comment]
Hey,

thanks a lot for your reply.

We are still planning out some of these details as we are shaping it our around your react grid but in its current shape I think we will be hoping to handle almost all sorting / filtering / grouping on the client side only, and due to the nature of our backend being an "all or nothing" API we likely will be doing a full data reload every x seconds (probably around 15 seconds). So the grid needs to maintain its sorting, grouping and filtering state while updating the new data.

The type of data transfer isn't fully decided yet, but it likely will be a full reload via HTTP GET request (likely using fetch) unless we decide to improve our backend to only push out actual data-changes in which case a WebSocket connection would perhaps make more sense.

The grid row should indeed be resorted when the new data is coming in and the same goes for any grouping and/or filtering. So basically, the grid needs to maintain its configuration state while its data state changes and apply that configuration state to the new data causing a redraw of relevant portions.

Thanks again!
