### ISSUE TITLE
How to use Custom editors in Inline Cell Editing

### ISSUE THREAD

**Issue by ahmetcaglayan** [DevExpress/devextreme-reactive#2682]
https://codesandbox.io/s/objective-dream-8mx4k

![13A85490-C403-4FDE-8ECB-F1D32D055057](https://user-images.githubusercontent.com/13018803/74739636-4e2ffc00-526a-11ea-908e-719e0848490f.jpeg)

When you first edit one of the "Shipped" cells and then click on other cells, they all remain in the editing state.

**Comment by AryamnovEugeniy** [comment]
Hello,

I updated [your example](https://codesandbox.io/s/muddy-haze-486kh). You can use any of the props defined in the `TableInlineCellEditing`'s [cellComponent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-inline-cell-editing/#tableinlinecelleditingcellprops). In this case, you need to use `onBlur` and `autoFocus` in order to manage the focus of your Select editor.
Does this solution meet your requirements?
