### ISSUE TITLE
text input loses focus on state change

### ISSUE THREAD

**Issue by neverend000** [DevExpress/devextreme-reactive#2750]
I had a similar problem as in [#2019](https://github.com/DevExpress/devextreme-reactive/issues/2019).

But instead of a class component, I use a functional component that does not have a render method.

Can you help me (and modify the example from [#2019](https://github.com/DevExpress/devextreme-reactive/issues/2019)) to understand how to work around this case ?

Greets!

**Comment by AryamnovEugeniy** [comment]
Hello,

I updated the example from the issue you mentioned. [Here](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-878x4) it is. The approach remains the same - define your custom component outside the render method (in case with functional components - outside a function body).

**Comment by neverend000** [comment]
Hi @AryamnovEugeniy! Thank you for the quick support!
But what should I do if I need to pass my own properties to the component? And I need to change state in the component. It broke again.
[Here](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-985km) updated example

**Comment by AryamnovEugeniy** [comment]
The main point is not to create a new component every time the Grid is rerendered. And `React`'s `useCallback` may help to solve your problem. Wrap your component in `useCallback` and rerender it only when props this component uses change. Here is the [updated example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-xrwlr) with `useCallback`.

**Comment by AryamnovEugeniy** [comment]
One more point. We have an article on our site on how to access parent component's state. Other methods are described there. It may be useful to you. [Here](https://devexpress.github.io/devextreme-reactive/react/common/docs/guides/performance-optimization/#access-the-parent-components-state-correctly) is that article.

**Comment by neverend000** [comment]
@AryamnovEugeniy Thanks for the answer, but let me explain what I really mean.

I am trying to validate a number field while editing and [update the example](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-985km) according to my code.

If you try to enter a character in the field, the focus will be lost, otherwise if you enter a number, everything will be ok.

I tried to wrap component in useCallback, but no success..

**Comment by neverend000** [comment]
P.S. If use a class component instead of a functional component and move custom components outside render method, everything works fine !
But I figure out what the problem is with the functional component ..

**Comment by neverend000** [comment]
any idea ?

**Comment by AryamnovEugeniy** [comment]
As I've said above, it is not advisable to create a new component on rerender, which is what happens even with useCallBack: every time `valid` prop changes, a new editor component is created (not just rerendered, which is fine, but created from scratch). That is why the focus is lost. And in your case this is crucial.

So, the solution is to avoid creating new Editor every time `valid` changes. And state management libraries, such as [Redux](https://redux.js.org/), may help you (see our [article](https://redux.js.org/) on how to access parent's state correctly) . Also, I've updated [your demo](https://codesandbox.io/s/devextreme-react-grid-for-material-ui-ewk0u).

One more point. It is better to use [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/#controlled-mode), as i've done, to validate your data instead of changing state field from inside render method, which may lead to errors.
