### ISSUE TITLE
GroupingPanel's itemComponent groups count customization

### ISSUE THREAD

**Issue by xde013** [DevExpress/devextreme-reactive#2864]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
### Description
I would like to get the number of groups and provide it to the itemComponent in the groupingPanel so it looks like something this:
![image](https://user-images.githubusercontent.com/21088699/80492944-ffd36380-8964-11ea-979e-c42e785e0d6d.png)
instead of the default component:
![image](https://user-images.githubusercontent.com/21088699/80493018-1d083200-8965-11ea-9560-bded1833ac7d.png)

Link to the [example](https://codesandbox.io/s/solitary-surf-j1p7q) (codesandbox)

### Environment

- devextreme-reactive: Latest to date
- react: Latest to date
- material-ui: Latest to date

Any help is appreciated 🙏

**Comment by AryamnovEugeniy** [comment]
Hello @xde013!

The solution to the issue will depend on your expected result. Please clarify what you would like to see when you group your data by several rows simultaneously. For instance, see the following screenshot where I group Grid's rows by two columns:
![image](https://user-images.githubusercontent.com/51905811/80687040-590cd580-8ad2-11ea-979e-52c0646e3d10.png)
Then, I expand several groups and get the following result:
![image](https://user-images.githubusercontent.com/51905811/80687194-9b361700-8ad2-11ea-926b-70b7e27d2dac.png)
As you can see, South America, North America, Africa, and Australia are displayed twice. If we expand more groups, there will be even more repetitions.
 
So, the question is what you expect to see in the first and in the second case.

**Comment by xde013** [comment]
Hey @AryamnovEugeniy, sorry my example wasn't clear (didn't cover the multiple groups case) in the general case I'm expecting to have the count of each group so in this example the number of products (4) and the number of regions (6).

**Comment by AryamnovEugeniy** [comment]
In this case I suggest you create a custom plugin ([here](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/custom-plugin-development/) you can find our article on the subject) and override the `rows` getter. You need to get access to the data inside the Grid and count unique data items in the columns you group by. And this is the number you are looking for. Remember that plugin order is important and if you, for example, use filtering, place your custom plugin **below** `IntegratedFiltering` so that you would not count the rows that have been filtered by the user.

After that you need to save this number (in my example, it is `groupCount` property) to your state and customize the `GroupingPanel`'s [itemComponent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/grouping-panel/#groupingpanelitemprops): just add the number you got to the column's title. Here is the [example](https://codesandbox.io/s/sharp-sound-o3160?file=/demo.tsx) which illustrates the approach I described.

Does this solution suit your needs?

**Comment by xde013** [comment]
@AryamnovEugeniy lgtm, thank you 👍

**Comment by AryamnovEugeniy** [comment]
You are welcome!
