### ISSUE TITLE
React Scheduler Getting Started example doesn't "just work"

### ISSUE THREAD

**Issue by gregfenton** [DevExpress/devextreme-reactive#2871]
- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [X] React Scheduler

### Current Behaviour
The instructions on the [React Scheduler Getting Started](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/getting-started/) page do not lend themselves to quick success.  There are dependencies that take effort to figure out.  A newbie will quickly tire and abandon hope :)

### Expected Behaviour
Straight-forward steps to getting up and running with a basic example of React Scheduler in a vanilla React app/environment.

### Steps to Reproduce
Following the instructions from the Getting Started page:

1. `$ npx create-react-app example-scheduler`
1. `$ cd example-scheduler`
1. `$ npm i --save @devexpress/dx-react-core @devexpress/dx-react-scheduler`
1. `$ npm i --save @devexpress/dx-react-scheduler-material-ui`
1. `$ npm install @material-ui/core`
1. `$ code .`
1. Edit App.jsx replacing its `return()` with the code from _Source_ tab of the [Getting Started example](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/guides/getting-started/)
    - you will also need to copy over the `import`s and the `const`s
1. `$ npm start`

This results in:
> Failed to compile.
>
>  ./node_modules/@devexpress/dx-react-scheduler-material-ui/dist/dx-react-scheduler-material-ui.es.js
>  Module not found: Can't resolve '@material-ui/icons/AccessTime'

So continuing on:
8.`$ npm install @material-ui/icons`
9.`$ npm start`

Results in:
> Compiled with warnings.
>
>   ./node_modules/moment/src/lib/locale/locales.js
>   Module not found: Can't resolve './locale'

And in the browser we get the error:
> Error: Cannot find module './locale'

This is apparently a known bug in moment, including 2.25.1.  See https://github.com/moment/moment/issues/4505
The posted solution is to downgrade to v2.24.0

So:
10. `$ npm install moment@2.24.0 --save`
11. `$ npm start`

**Now we have a working basic example -- HURRAY!!**

[**NOTE**: the use of different styles of _npm_ commands comes from following instructions linked to from the Getting Started page.  As a "newbie", I'm going by what I'm instructed to do.  That said, I don't think changing the npm commands to all be consistent (`i` vs. `--install`, with or without `--save`) will resolve the core issue.]

### Environment

- @devexpress/dx-react-core: 2.6.2
- @devexpress/dx-react-scheduler: 2.6.2
- devextreme-reactive: none
- react: 16.13.1
- browser: Chrome on MacOS - 81.0.4044.122 (Official Build) (64-bit)
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.9.12

**Comment by AryamnovEugeniy** [comment]
Hello @gregfenton!

Thank you for your feedback. We strive to make our resources intuitive and reduce the learning curve.

On our `Getting Started` page we specify commands that are required to install the Scheduler. However, we use external frameworks, such as [Material-UI](https://material-ui.com/), to implement visual components. The Scheduler has only one package with visual components: `@devexpress/dx-react-scheduler-material-ui`, but our Grid has three packages. Some users may even choose to use themeless packages and implement visual components. So, it is necessary for us to separate themeless packages and packages with visual components. Users will need to install and configure the framework they want to use. Since `Material-UI` is an external framework, we cannot give their installation guide on our `Getting Started` page. What we can do is to share all the necessary links with information on how to install it, and that is what we do on our `Getting Started` page.

 

**What we can do**: we can provide additional information to specify what components should be configured for a specific framework before users can start using our components (for instance, users need to install `Material-UI`'s core and icons to use the Scheduler).

**What we cannot do**: we cannot provide a guide on how to configure `Material-UI` or `Bootstrap` on our `Getting Started` pages and thus make the commands consistent.

 

As for `moment`, we use this library to implement a part of the Scheduler's functionality. The moment team released 2.25.0 on May, 1. That minor release contained the bug you mentioned. And npm downloaded the latest version of this library when you were installing the Scheduler. By that time we were not aware of the issue. Since then, the moment team already released 2.25.3, which fixes the problem you encountered and it should not lead to other issues.

 

We are constantly working on our components and documentation and take our users’ feedback into account. We would appreciate it if you share your opinion of how the `Getting Started` page may be improved.

**Comment by gregfenton** [comment]
The main question is: do you want to provide instructions to get someone up-and-running with a demo, or are you willing to risk that they fail and walk away?

There are many modules in open source land that give instructions on "one way to get started" that include configuring various third party modules as well.  Just make it clear that these instructions are "for demonstration purposes only" and that for their own development projects they may/likely need to follow other instructions for those third parties.

Without clear, step-by-step instructions on just getting the system up and running, newcomers will be confused and frustrated.  This doesn't bode well for an open source project's success.

**Comment by AryamnovEugeniy** [comment]
Thank you for your feedback! I discussed your suggestions with the team and we decided to take them into account in the future.

If you have any other question, we will be happy to answer it.
