### ISSUE TITLE
Is there a way to only make the "Save" button on the TableEditColumn appear?

### ISSUE THREAD

**Issue by stmchan93** [DevExpress/devextreme-reactive#2886]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

My question is around being able to use a custom popup to do actions like save and edit on a grid without using the TableEditColumn component. Is there a callback for saving and updating outside of the Template Plugin I can use to do this? For example I have a popover that shows the "Edit" button. When you click the "Edit" button, the entire table is editable, and the "Save" button appears next to each row. Then when you click "Save" on one of the rows, all of the changes in the table are committed.

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by AryamnovEugeniy** [comment]
Hello,

I suggest you use [Editing in Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/editing/#controlled-mode). In this case, you can save all the changes in your state. You can add all the rows to the `editingRowIds` on, for example, a custom button click (and they will be in editing mode). Here is an example: https://codesandbox.io/s/exciting-morse-yhc7z?file=/demo.js
In this example I add all the rows to `editingRowIds` on `Edit` button click. I've also customized `TableEditingColumn` [commandComponent](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-edit-column/#tableeditcolumncommandprops): I've hidden cancel button and changed commandButton's`onExecute` property to save all of the rows at once on `Save` click.

Does this solution suit your needs?

**Comment by stmchan93** [comment]
Great! This is awesome and works for me. Thank you @AryamnovEugeniy . I have just one question - is it possible to put the edit button in the left of the paging panel? I see that on the paging panel component there is a lot of space to the left of the paging panel and wanted to put the edit button there.

**Comment by stmchan93** [comment]
Also, is there a way to have the "New" button when you create a new row, to add to the bottom of the grid instead of the top?

**Comment by AryamnovEugeniy** [comment]
Hello again!

I updated the previous example. Here is the new one: https://codesandbox.io/s/exciting-morse-yhc7z?file=/demo.js.
In my example I've overridden the `tableBodyRows` [Getter](https://devexpress.github.io/devextreme-reactive/react/core/docs/reference/getter/). The first N (`addedRowsAmount`) of the rows in this getter are the added rows. I've removed them from the beginning of the `tableBodyRows` array and placed them in the end (but first I've changed their order).
Note: this getter must be placed **after** `TableEditRow` plugin (see our article on [plugin order](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/plugin-overview/#plugin-order)) since your custom getter depends on this plugin.

Does this solution suit you?

**Comment by stmchan93** [comment]
yes! perfect. thank you!

**Comment by AryamnovEugeniy** [comment]
You are welcome!
