### ISSUE TITLE
VirtualTable TableColumnResizing with 'nextColumn' and percentages bad behavior

### ISSUE THREAD

**Issue by MattShrider** [DevExpress/devextreme-reactive#2976]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

When a VirtualTable is configureed with TableColumnResizing in `nextColumn` resizing mode, and uses percentages or 'auto' sizing for column widths, the widths start out incorrect, and attempting to resize a column makes all of the widths reset, and a new invisible "fake" column gets added to the end of the table DOM, breaking resizing the final column.

### Expected Behaviour

I want to be able to set up each column to take up 10% grid width, while the final column is 'auto' to take up the rest of the grid width. This seems to work using a normal `Table`, but I use `VirtualTable` for my use case.

An alternative would be to be able to use percentages and auto with 'widget' resizing as well.

### Steps to Reproduce

Link to the example that reproduces the issue: https://codesandbox.io/s/compassionate-wood-5if9q?file=/demo.js

### Screenshots

![image](https://user-images.githubusercontent.com/5342565/86967708-00446380-c139-11ea-96f0-eb28b1758932.png)

### Environment

- @devexpress/dx-react-grid 2.6.4
- react: 16.13.1
- browser: chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.10.0

**Comment by MattShrider** [comment]
It seems like the bug only happens if you resize the 'auto' column, without first resizing the first column. (In my example, resize car first)

**Comment by LazyLahtak** [comment]
Hi @MattShrider,

The `TableColumnResizing` plugin supports only column width described in [Table.columnExtensions](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#tablecolumnextension) and [VirtualTable.columnExtensions](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/virtual-table/#virtualtablecolumnextension) for the `Table` and `VirtualTable` respectively. Due to the way the grid is rendered for the Virtual Table, we can’t calculate the width of columns for relative CSS units like `em`, `%`, `auto` and others. Thus, the `VirtualTable` supports only column width in pixels.

If you have any further questions, feel free to contact us.
