### ISSUE TITLE
Disabling Table animation or fix issues ?

### ISSUE THREAD

**Issue by woodreamz** [DevExpress/devextreme-reactive#3002]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

Animations on the Grid seems to have strange behavior.

Old issues were closed without any fixes:
#1529 (The workaround is working well but it is a workaround...)
#1920

Those issues were opened more than one year ago.

### Expected Behaviour

Animations should work correctly or provide us a way to disable animations. In any case, we should be able to disable animations because if we use Virtual Table and Table in the same webapp, the behavior is different (Virtual Table has no animations). We should be able to uniformize the behavior.

### Steps to Reproduce

See linked issue.

### Environment

- devextreme-reactive: 2.7.0
- react: 16.13.1
- material-ui: 2.7.0

**Comment by LazyLahtak** [comment]
Hi @woodreamz,

Could you please clarify what issue with animation you encountered? To disable animation for the Table, you can customize the [Table.Cell](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#tabledatacellprops) and [TableHeaderRow.Cell](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-header-row/#tableheaderrowcellprops) components. I suggest that you remove `transform` from the `style` property of these components. Here is an [example](https://codesandbox.io/s/vigorous-spence-8twn8?file=/demo.js).

**Comment by woodreamz** [comment]
Hi,

I encounter the issue #1529 and #1920 (#2120 too). The workaround you provide is similar to the one provided in #1529, and it's working fine. As the VirtualTable does not have any animations, we should have an option to disable the animations to standardize the behaviour of the two tables if used in the same webapp.

I am very happy to have a quick answer from you with a workaround for short term but I am also expecting that we will have a fix for long term. Honestly, I created some issues and read a lot and I have the feeling you provide a workaround for each issue and the issue is closed automatically and we will never see a fix.

You closed those three issues by referring a solution in [this comment](https://github.com/DevExpress/devextreme-reactive/issues/2120) but once again, it's a workaround. We must be able to use string value (for the width) in [defaultColumnWidths](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-column-resizing/#tablecolumnwidthinfo).

**Comment by LazyLahtak** [comment]
The problems in #1529 and #2120 occurred because the `TableColumnResizing` plugin was provided with properties of the incorrect type (`string` instead of `number`). Prior to version [2.0.5](https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md#205-2019-09-16), we supported only `number` width for columns, and it wasn't a bug with animation.

With the [2.0.5](https://github.com/DevExpress/devextreme-reactive/blob/master/CHANGELOG.md#205-2019-09-16) release, we improved column sizing and allowed the use of the `string` type for the Table and VirtualTable, and CSS-accepted units for the Table (please refer to [Table.ColumnExtension](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#tablecolumnextension) and [VirtualTable.ColumnExtension](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/virtual-table/#virtualtablecolumnextension)). We also added new information about supported types to our [documentation](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-column-resizing/#tablecolumnwidthinfo). Here is an [example](https://codesandbox.io/s/objective-dawn-ccm0h?file=/demo.js).

Issue #1920 referenced issues #1529 because [its ](https://github.com/DevExpress/devextreme-reactive/issues/1529#issuecomment-433225533)[comment](https://github.com/DevExpress/devextreme-reactive/issues/1529#issuecomment-433225533) contains a suitable solution. Currently, we have no option to disable Table animation, but we will take your suggestions into account. You can check our [roadmap](https://js.devexpress.com/Roadmap/#ReactComponents) to be informed about our new features.

Please let us know if you encountered any problem with animation. Also, feel free to open a new issue if you have any questions or suggestions.
