### ISSUE TITLE
React Grid Virtual Scrolling with remote data Lazy loading within grouped panel expanded row data

### ISSUE THREAD

**Issue by FayezX** [DevExpress/devextreme-reactive#3035]
I have searched this repository's issues and believe that this is not a duplicate.
I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Schedule

### Issue

I am trying to have Virtual Scrolling with remote data Lazy loading in both the outer level of the grouped data along with when we expand the grouped panel, the data rows being expanded have a certain height and I want to be able to configure that as well in lazy loading fashion where if we scroll down it makes data requests and updates that grouped data as well. Any insight into this would be helpful or a small demo of how to approach this.

**Comment by LazyLahtak** [comment]
Hi @FayezX,

The additional space appeared, because the `totalRowCount` gotten from server doesn't take into account expanded groups. For remote grouping you need to recalculate the total row number given grouped rows and expanded groups. Here is an [example](https://codesandbox.io/s/distracted-smoke-x2nje).
If you have any further questions, feel free to contact us.
