### ISSUE TITLE
Is there a way to always hide a column and not having it appear on the visibility toggle?

### ISSUE THREAD

**Issue by KLagdani** [DevExpress/devextreme-reactive#3038]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

In the following codesandbox: https://codesandbox.io/s/shy-https-mn5t9?file=/demo.js

The column city is hidden and it should always be hidden. Is there a way to hide it from the visibility Toggle as well?
The idea is that I need the data in this column for my code but I don't want it to be visible for the user.

Screenshot:
I want to hide the City box on here:
![image](https://user-images.githubusercontent.com/21138162/90250616-9d7f6f80-de3c-11ea-947c-971e04796198.png)

**Comment by LazyLahtak** [comment]
Hi @KLagdani.

I suggest that you define a custom [ColumnChooser.Item](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/column-chooser/#columnchooseritemprops) component. In this component, you can return the `null` value instead of the element for disabled and hidden columns. Here is an updated [example](https://codesandbox.io/s/intelligent-shockley-td81t).
If you have any further questions, feel free to contact us.

**Comment by KLagdani** [comment]
Great, thank you!

**Comment by LazyLahtak** [comment]
You are welcome!
