### ISSUE TITLE
AppointmentForm anchor right

### ISSUE THREAD

**Issue by vinniimiranda** [DevExpress/devextreme-reactive#3039]
- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [X] React Scheduler

### Description
I would like to open the AppointmentForm on the right side of whe screen, once the lib it's using Drawer of Material UI, should be possible to pass the anchor for the AppointmentForm

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment

- @devexpress/dx-react-scheduler: 2.7.0
- @devexpress/dx-react-scheduler-material-ui: 2.7.0
- react: 16.13.1
- browser: Edge
- material-ui: 4.11.0

**Comment by AryamnovEugeniy** [comment]
Hello!

It is possible to customize AppointmentForm's [Overlay](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/appointment-form/#appointmentformoverlayprops) and pass to it `anchor="right"` prop. But it won't work correctly due to this Material-UI bug: https://github.com/mui-org/material-ui/issues/16463.

If you have any other questions, we will happily answer them.

**Comment by vinniimiranda** [comment]
Thanks for the quickly response.
