### ISSUE TITLE
How to show more data in Appointment without deleting the default data shown

### ISSUE THREAD

**Issue by Sebcrk** [DevExpress/devextreme-reactive#3052]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

Hi, I'm trying to show some custom data fields in the appointment but so far I've seen that the AppointmentContent has to be completely changed #2008 in order to achieve this. I'm wondering if it's possible now. 

### Environment

- devextreme-reactive: 2.7.0
- react: 16.13.1
- chrome: 84.0.4147.105
- material-ui: 4.11.0

**Comment by AryamnovEugeniy** [comment]
Hello!

The situation hasn't changed since then. You need to follow the advice from the issue you mentioned. Also, you may use this demo as an example: https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/integrated-data-shaping/

If you have any other questions, we will be happy to assist you!
