### ISSUE TITLE
Getting started with Firebase

### ISSUE THREAD

**Issue by christoshrousis** [DevExpress/devextreme-reactive#307]
Does anyone have any suggestions or examples I could follow for integrating this with a Firebase database? 

I know each database can be unique but I'm a little stuck at where to start.

**Comment by kvet** [comment]
Hi,

We do not have an example with Firebase. We assume that Grid can be easily integrated with any server technologies. See the following example demonstrating remote data loading: https://devexpress.github.io/devextreme-reactive/react/grid/demos/featured/remote-data/

In order to fetch data from Firebase, you can use one of the following ways:
- Firebase REST API: https://firebase.google.com/docs/reference/rest/database/
- Firebase WEB API: https://firebase.google.com/docs/database/web/lists-of-data

You can also refer to the following blog post: https://community.devexpress.com/blogs/oliver/archive/2017/07/10/devextreme-react-grid-remote-data-real-world-patterns .aspx

Feel free to contact us at any time.

**Comment by kvet** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.

**Comment by predorock** [comment]
Hi,
I am creating an application with Angular6 + FireStore + NgRX. There's any suggestion how to implement "reactive" patterns with DevExtreme widgets? Grids for examples? Thanks
