### ISSUE TITLE
Passing custom props to toolbar rootComponent with Searching plugin enabled

### ISSUE THREAD

**Issue by bahamut657** [DevExpress/devextreme-reactive#3075]
# I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description
I'm using a custom rootComponent for the Toolbar plugin:

1. I create a custom component for rendering the toolbar
2. I use connectProps to pass some props from the root component to the toolbar custom component
3. Using the Search plugin, every time I press a key, the search input is blurred

How can I prevent the blur on the Search field?

**Comment by AryamnovEugeniy** [comment]
Hello!

One possible cause of such a behaviour is that the Search's input is unmounted and again mounted whenever you try to type a symbol into it. Like in this example, for instance: https://codesandbox.io/s/unruffled-bouman-p841v?file=/demo.js (I did not use `connectProps` or anything like this to make my example as simple as possible).
But if I add memoization (with the help of `useCallback`) so that Search's input is not unmounted unnecessarily, everything works correctly: https://codesandbox.io/s/upbeat-bassi-9il90?file=/demo.js.

So, I advise to check whether your memoization works correctly. Let me know if this is helpful. If this is not, could you make an example demonstrating your issue?

**Comment by bahamut657** [comment]
Hi!
Following your example and using the `useCallback` I can solve the problem.
This issue can be closed.

Thank you so much

**Comment by AryamnovEugeniy** [comment]
I'm glad that it helped!
