### ISSUE TITLE
The order of selected items after using select-all doesn't look correct

### ISSUE THREAD

**Issue by abhimanyusirohi** [DevExpress/devextreme-reactive#3085]
- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [X] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Here's a Sandbox link to the problem: https://codesandbox.io/s/devx-react-grid-selection-order-xvoj5?file=/demo.js

There are 5 items in the list and this demo prints the selected items to the console as it changes.

When I use the select-all checkbox in the Name column (when nothing is selected) I can see that the order is `[0, 1, 2, 3, 4]
`. Then I deselect all and select just the second item in the list and then again use select-all checkbox. Notice that the order is `[1, 0, 2, 3, 4]` so the select-all command is working over the current selection when I think it should work by clearing the current selection and then selecting all items. Is this order expected?

### Environment

- devextreme-reactive: 2.7.1
- react: 16.13.1
- browser: Chrome
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by AryamnovEugeniy** [comment]
Hello!

This order is expected because we do not clear the previously selected cells, we just add the newly selected ones to the previous selection.
If you need to change this order you may use Selection in the [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/#controlled-mode).
