### ISSUE TITLE
[AppointmentTooltip.Header] Fetch background from file

### ISSUE THREAD

**Issue by GRawhideMart** [DevExpress/devextreme-reactive#3122]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ ] React Grid
- [ ] React Chart
- [x] React Scheduler

### Description

Hello, it's me again. I was dealing with the AppointmentTooltip.Header component, starting from [this](https://codesandbox.io/s/g4nlb?file=/demo.js:1561-1614) example.
My situation is turning out to be quite hard to adapt: in this example a class is defined for every room, which is fine because the rooms are just three.

In [this](https://codesandbox.io/s/priceless-thunder-untrd) sandbox, what I actually want to do is, in the StudioScheduler component defined inside `src/SchedulerComponent.js`, make it so that every program (which is a JSON object defined inside `shared/programmi.js`) has its own backgroundColor and backgroundImage in the tooltip header; both the background color and the background image are defined inside the JSON object. How can I do this? I can't map every program to a class, since the programs change.

Every help will be, as usual, very much appreciated.

### Environment

- devextreme-reactive: 2.7.1
- react: 16.13.1
- browser: Microsoft Edge
- bootstrap: none
- react-bootstrap: none
- material-ui: 4.11.0

**Comment by AryamnovEugeniy** [comment]
Hello!

It seems that you can use Material-UI's [makeStyles](https://material-ui.com/styles/basics/#hook-api). Here is a small example (I updated one of our demos because your example just would not load on my side): https://codesandbox.io/s/distracted-water-i3eyw?file=/demo.js.
Another option is to use `style` property:
```
style={{ background: `url(${appointmentData.imageURL})` }}
```

Should you encounter any other issue, we will be happy to help you!
