### ISSUE TITLE
Grid width not correct inside a flex container

### ISSUE THREAD

**Issue by QuentinLuc** [DevExpress/devextreme-reactive#3181]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

Hey!  When the Grid is embed inside a flex container, its width is not computed correctly because columns without a predefined size take too much place.  Also these columns without size defined do not resize automatically (only when the grid is inside a flex container, otherwise it works fine).  The situation also happens inside a "display:grid" container.
It means that after you resized the browser's window, you have to refresh the page to partially fix the width.  The column size is better but not always as small as it should be.  I think the minium width of a column is 120px based on the tests I've made but sometimes, even after a refresh, it's still bigger.

I'd expect the grid to behave the same wether it's in a flex container or inside a normal div container.

You can find an exemple here: https://codesandbox.io/s/spring-meadow-gqtvn?file=/demo.js

On the first printscreen, the size is correct.  And on the second I expended the window and then resize it to its original size and the width of the grid is not correct anymore.

<img width="835" alt="Screenshot 2020-11-18 at 15 30 26" src="https://user-images.githubusercontent.com/5237095/99543082-0b46b480-29b3-11eb-9fb3-b927584fe95f.png">
<img width="772" alt="Screenshot 2020-11-18 at 15 30 43" src="https://user-images.githubusercontent.com/5237095/99543075-0a158780-29b3-11eb-8dc4-623bd2704492.png">

Dependencies
- @devexpress/dx-react-core: 2.7.3
- @devexpress/dx-react-grid: 2.7.3
- @devexpress/dx-react-grid-material-ui: 2.7.3
- @material-ui/core: ^4.11.0 (4.11.0)
- @material-ui/icons: ^4.9.1 (4.9.1)
- react: ^16.14.0 (16.14.0)
- react-dom:latest (17.0.1)

**Comment by LazyLahtak** [comment]
Hi @QuentinLuc,

Thank you for your interest in our React Grid.
We calculate column width for the Virtual Table manually. The default minimum width of each column is `120px`. The actual width is calculated based on the container width and the size of non-fixed columns.
In your example, 4 out of 5 columns have fixed width. The "Product" column resizes dynamically when the container expands because additional space becomes available and non-fixed columns try to fit into it. When the container shrinks, its width is reduced. For this reason, non-fixed columns don't change their width. Unfortunately, in the current implementation, there is no way to recalculate the size of these columns automatically.
I suggest that you fix the size of all columns using the [columnExtensions](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/virtual-table/#virtualtablecolumnextension) property. This will help you avoid the change of column width. If you need to expand some columns, I suggest that you use a solution from this thread: [#2997 (comment)](https://github.com/DevExpress/devextreme-reactive/issues/2997#issuecomment-661695516). In this thread, we use the [react-resize-detector](https://www.npmjs.com/package/react-resize-detector) to detect the resizing of the Grid and to change column width. This solution also works with `columnExtensions`.

Let me know if it meets your requirements.
