### ISSUE TITLE
Checkbox disabled

### ISSUE THREAD

**Issue by Durairaj** [DevExpress/devextreme-reactive#323]
I am trying with the material ui. The selection props are getting updated, but the tick is not reflected in the row for the selection. Also i see the checkbox in the header is disabled. any reason?

![image](https://user-images.githubusercontent.com/201747/30186734-ac172760-941e-11e7-8eaa-4e9e07195165.png)

**Comment by kvet** [comment]
Hi,

The issue is not completely clear to me. Would you please provide us with a simple example that shows the issue? With an example, it is much easier for us to verify that the code that calls ours is valid and that the way our controls are being used is recommended.
Your time and cooperation are greatly appreciated.

**Comment by Durairaj** [comment]
Something bad with component state of row before rendering
