### ISSUE TITLE
Grid - TableRowDetail is not displayed if VirtualTableState is used and loaded data is less than page size

### ISSUE THREAD

**Issue by DevExpressSupportTeam** [DevExpress/devextreme-reactive#3235]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.
### I'm using ...
- [x] Reactive Grid
### Info
Example: <a href="https://codesandbox.io/s/dazzling-ganguly-y102s?file=/demo.js">https://codesandbox.io/s/dazzling-ganguly-y102s?file=/demo.js</a>

**Steps:**

- Open the example
- Try expanding the first row

**Actual Results:**

Detail data is not visible

**Expected Results:**

Detail data should be visible after expansion

**Comment by artem-kurchenko** [comment]
Hi ,

Thank you for your patience. We tried several ways to fix this behavior but none of them were flexible enough to cover all cases with scrolling. The problem is that the current lazy loading implementation relies on the fact that all loaded rows are data rows. It doesn't take into account that some rows are displayed as additional information.

To fully support this functionality at the component level, we need to significantly change the current calculation mechanism. Though we don't plan to perform such changes in the near future, we found alternative solutions:

* you can implement a popup window to display detail data on a row click: [CodeSandBox #1](https://codesandbox.io/s/reactive-grid-display-details-in-popup-7uscf?file=/demo.js)
* you can change the current loading mechanism and use the solution we described at [VirtualTableState not optimized for cursor pagination](https://github.com/DevExpress/devextreme-reactive/issues/2850). Here is an example that demonstrates this idea: [CodeSandBox #2](https://codesandbox.io/s/sad-rhodes-dcvh5)

**Comment by chanand** [comment]
Basically you are saying that your `virtualTable` is not usable with Detail Rows, which is unmentioned in your documentation.

We need a lazy loading grid with detail rows. Using a popup is not a viable option because the UX is not right.
Using `onTopRowChange` as suggested does not help because we need to be able to scroll all the way through the table, and by using `onTopRowChange` we get a different UX then we'd expect that feels weird.

**Comment by artem-kurchenko** [comment]
Yes, the `Lazy Loading` feature is not compatible with DetailRow at the moment. I'm not sure about your comment for "onTopRowChange ". [Infinite Scrolling](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/lazy-loading/#infinite-scrolling) and the solution with `onTopRowChange ` work very similarly on my side and allow scrolling through all records. I've attached a screencast to demonstrate how scrolling works in both modes on my side. Could you clarify where the difference comes?

https://user-images.githubusercontent.com/22076961/107075977-e9174280-67fb-11eb-8110-c87db636a1fd.mp4


We're also researching alternative options. I'll update here once we come up with any results.

**Comment by chanand** [comment]
I'd expect a virtual scroll to indicate the full height of table as if it has all rows (based on total count?), and not to change as you scroll and load more data.

**Comment by artem-kurchenko** [comment]
Thank you for the clarification. In this case, the `infiniteScrolling` option is unnecessary as it doesn't produce the behavior you require. The main challenge in this particular scenario is to overcome the grid's internal cache. This cache cannot be accessed via the current API but needs to be recalculated when a user scrolls the table. Taking these things into account, we found that it's possible to implement the following solution:

1. Use the DetailRow plugin in the Controlled Mode to know how many expanded rows you have.
2. Adjust the query logic and reset the `expandedRowIds` parameter when new data is being loaded.
3. Adjust the `take` parameter to take into account the number of previously expanded rows.


Here is an example that demonstrates this idea: [CodeSandBox](https://codesandbox.io/s/peaceful-pike-ie716?file=/demo.js)

Note that all previously expanded rows will be collapsed after the Grid component loads a new set of records. This is required to overcome the current caching mechanism I mentioned above.

**Comment by chanand** [comment]
The hacky workaround seems to work.

Thanks.
