### ISSUE TITLE
Row reordering workaround causing severe peformance drop

### ISSUE THREAD

**Issue by rrajaste** [DevExpress/devextreme-reactive#3248]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

Using the row reordering workaround provided in #419 (react-sortable-hoc) together with column reordering plugin causes severe lag when reordering columns, even in production mode.

### Expected Behaviour

Column reordering should work smoothly together with row reordering workaround.

### Steps to Reproduce

Link to the example that reproduces the issue: https://codesandbox.io/s/devextreme-react-grid-for-material-ui-forked-nwmm8?file=/index.js

**Comment by LazyLahtak** [comment]
Hi @rrajaste,

Thank you for your interest in our React Grid!

We researched this issue and found that the `react-sortable-hoc` library is not suitable for our architecture. Using HOC with our components may cause a performance drop.
We plan to add a Row Reordering demo with another library. For now, we are refactoring our components to make them more flexible when working with third party libraries.
If you need this feature now, you can use our [DataGrid for React](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/LocalReordering/React/Light/).

If you have any further questions, feel free to contact us.

**Comment by gfox1984** [comment]
Do you have an ETA for proper row reordering? I see this has been a request since a few years, but it is still not here. With the refactoring you are working on, will you forward a ref to the TR elements used in the grid, so that it's easier to use with a third party library such as `react-beautiful-dnd` or `react-dnd`?

**Comment by ionescho** [comment]
+1 for ETA ? DataGrid for React is not an option since we have build a whole library around Devextreme Reactive.
Also I have tried using  react-beautiful-dnd but this does not work as Table.Row and Table.Body do not support refs.
This here doesn't work: https://codesandbox.io/s/devextreme-react-grid-for-material-ui-forked-svrz4?file=/index.js
