### ISSUE TITLE
Grouping causing severe performance drop

### ISSUE THREAD

**Issue by emadsamir** [DevExpress/devextreme-reactive#3260]
- [ ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

No matter what you try, small data or not, even in demos, once you enable grouping, rendering is painfully slow, especially on weekly view.

### Expected Behaviour

Performance shouldn't be impacted.

### Steps to Reproduce

Link to the example that reproduces the issue: &lt;put your link here&gt; (you can fork one of our pre-configured [examples on CodeSandbox](https://github.com/DevExpress/devextreme-reactive/issues/2358)).

### Environment

- devextreme-reactive: latest
- react: latest
- browser: any
- bootstrap: na
- react-bootstrap: na
- material-ui: latest

**Comment by AryamnovEugeniy** [comment]
Hello!

I checked our [demo](https://devexpress.github.io/devextreme-reactive/react/scheduler/demos/featured/appearance-customization/) and it works all right. Could you provide us with an example when grouping works slower than expected?

Note: when grouping is used, the scheduler will have to render more cells (and, possibly, appointments) than without grouping. And it is expected that it will take more time to render. When rendering a lot of groups, we advise you to use [production mode](https://reactjs.org/docs/optimizing-performance.html#use-the-production-build) instead of development mode.

**Comment by emadsamir** [comment]
Thanks for the response.
I do understand the point of rendering more cells "initially", what I am reporting is an issue with rendering the events as you change date, even if data is static like in demo. The ratio of rendering the same events grouped vs non-grouped is like 10:1

**Comment by ajorkowski** [comment]
I noticed this issue too, and one thing I think that is causing this issue is that a different key is used when the date of the cell changes, which means React will be replacing every cell when you change weeks on the calendar (especially for week view). I got around this by hacking the key so that it is the same for every weekday - this way the cells can be reused. I also set the startDate/endDate to null so that the inner cell can be memonized too, but I think this can be optional.

Example code below:

```
<WeekView
  timeTableRowComponent={WeekViewTableRow}
  ...
/>

const WeekViewTableRow = memo(function WeekViewTableRow({ children }) {
  // NOTE: we are overloading this class for performance reasons, changing the key below halfs the rendering time of the calendar
  // as cells are reused based on the day of the week (not by the actual date)
  return <WeekView.TimeTableRow>
    { children.map(c => {
      const { startDate, groupingInfo } = c.props;
      const day = startDate.getDay() + '';
      const key = groupingInfo ? groupingInfo.reduce((acc, group) => acc.concat(group.id), day) : day;
      return cloneElement(c, { key, startDate: undefined, endDate: undefined });
    }) }
  </WeekView.TimeTableRow>;
});
```

The performance is far more acceptable with the changes above.

**Comment by emadsamir** [comment]
Thanks @ajorkowski for taking the time to respond, I will check your solution and be sure to report back.
This however confirms there's an issue that needs to be addressed.

**Comment by eyounis** [comment]
I am also experiencing this in V3, the rerending of the grouping type every time the view is changed is an absolute performance killer.
Please take this seriously and provide a permanent solution.
