### ISSUE TITLE
Resizing columns when using the default width crashes

### ISSUE THREAD

**Issue by mwilli20** [DevExpress/devextreme-reactive#3299]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Current Behaviour

When you go to resize a column when using the default widths, the React app crashes.

### Expected Behaviour

You would be able to resize a column even if no default width is provided.

### Steps to Reproduce

https://codesandbox.io/s/prod-lake-l6etd?file=/demo.js:565-624

Which is a slight modification to https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-resizing/ where we don't provide widths.

**Comment by mwilli20** [comment]
Following the stack trace it seems the issue comes from:

https://github.com/DevExpress/devextreme-reactive/blob/5aa943c08b346a72270928cd04fdd940f5249e8d/packages/dx-grid-core/src/plugins/table-column-resizing/helpers.ts#L3-L25

TypeError
Cannot read property 'width' of undefined

Looks like this happens because https://github.com/DevExpress/devextreme-reactive/blob/5aa943c08b346a72270928cd04fdd940f5249e8d/packages/dx-grid-core/src/plugins/table-column-resizing/helpers.ts#L8 actually should be optional, and since it isn't defined.

It crashes https://github.com/DevExpress/devextreme-reactive/blob/5aa943c08b346a72270928cd04fdd940f5249e8d/packages/dx-grid-core/src/plugins/table-column-resizing/helpers.ts#L10-L12 as that value is not there. 

I imagine checking for undefined needs to happen in that first and not use ! for the ts on line 8.

**Comment by AryamnovEugeniy** [comment]
Hello!

Reactive Grid and its plugins support two modes: [Controlled ](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/#controlled-mode)and [Uncontrolled](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/controlled-and-uncontrolled-modes/#uncontrolled-mode). So, in case of column resizing you need to provide either `columnWidths` and `onColumnWidthsChange` (that would be [Controlled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-resizing/#controlled-mode)) or `defaultColumnWidths` (that would be [Uncontrolled Mode](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-resizing/#uncontrolled-mode)).
Also, we specify in [our docs](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/column-resizing/#uncontrolled-mode) that `defaultColumnWidths` must define every column's width; otherwise, the Grid will throw an error. And this is what happened in your case.
So, in this case the solution is to pass `defaultColumnWidths` to the `TableColumnResizing` plugin.

If you have any other questions, we will be happy to assist you!

**Comment by mwilli20** [comment]
@AryamnovEugeniy Maybe this shouldn't be marked as a bug, but possibly an enhancement? I feel like there should be a simple way to take the default column widths provided, and be able to resize if desired. The default size depends on the size of the device previewing and naturally works quite well.
