### ISSUE TITLE
How to style PagingState active Button.

### ISSUE THREAD

**Issue by lcanavesio** [DevExpress/devextreme-reactive#3309]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [x ] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

Similary https://github.com/DevExpress/devextreme-reactive/issues/1021 but PagingState does not have Property 'containerComponent' 

 How to style PagingState? 

I need to style the active page button but cannot find a way around it.

Path: devextreme-reactive/packages/dx-react-grid-material-ui/src/templates/paging-panel/pagination.jsx contains the style:

activeButton: {
    fontWeight: 'bold',
    cursor: 'default',
  },

And i need add background: #b6b6b6 but I can't assign it.

Thanks a lot.

### Environment

-  devextreme": "20.1.4",
-  "devextreme-react": "20.2.6",
- "@devexpress/dx-react-grid": "^2.7.2",
- "@devexpress/dx-react-grid-material-ui": "^2.7.2",
- "react": "^17.0.1",
- "next": "^10.0.6",
- browser: Chrome
- "@material-ui/core": "^4.11.0",

**Comment by lcanavesio** [comment]
Hi @LazyLahtak ! How could I do it?

**Comment by threepears** [comment]
As this is not yet something users have access to, it looks like, I am currently preparing a PR that will let you pass in a class of your own as a prop when you create a grid.  That class will then get added to the `activeButton` so that you can style it.

Currently, however, the solution I have coded is only implemented for the Material UI setup and not for the Bootstrap version, as that at least has some nice styling to it already where the current active page stands out (most of the asks I've seen online about this were for Material users anyway, it seemed to me).  Not sure who to ask about this, but should I also look into spending a little time implementing the solution for Bootstrap as well?  I was thinking of posting the PR first to see if the solution was acceptable, and then branching out if requested.  @LazyLahtak , are you the person to check in with?

**Comment by threepears** [comment]
This is now done and waiting for comment ... located here : https://github.com/DevExpress/devextreme-reactive/pull/3366

**Comment by lcanavesio** [comment]
@threepears Excellent! Very good work. I hope they approve
