### ISSUE TITLE
TableRowDetail with Tree Data 

### ISSUE THREAD

**Issue by khchine5** [DevExpress/devextreme-reactive#3325]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

- [ x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

I am using the Tree Data of  React Grid and I want to show a detail only for the last child row. [here an example (https://codesandbox.io/s/cold-bush-dpbie?file=/demo.js) ] 
Thanks

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by LazyLahtak** [comment]
Hi @khchine5,

I suggest you customize the [TableRowDetail.ToggleCell](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-row-detail/#tablerowdetailtogglecellprops) component. This way, you can detect if the current row has children rows. If it does, you can render `Table.Cell` or `Table.StubCell` instead of `TableRowDetail.ToggleCell`. Here is an [example](https://codesandbox.io/s/eager-sun-slvbi).

Please let me know if you require any clarification.
