### ISSUE TITLE
Multi selection / Mixed selection with hidden checkboxes (like in old Devextreme)

### ISSUE THREAD

**Issue by zdzarsky** [DevExpress/devextreme-reactive#3348]
### I'm using ...

- [x] React Grid
- [ ] React Chart
- [ ] React Scheduler

### Description

In sophisticated systems it's very useful to have single selection by default and multiselection as an additional option.
Having separate usage contexts for both is very useful.

As a user I'd like to have a possibility to use MixedSelection in controlled and uncontrolled mode. I[t's already realised by Devextreme Datagrid ](https://js.devexpress.com/Demos/WidgetsGallery/Demo/DataGrid/MultipleRecordSelectionModes/React/MaterialBlueLight/)
I understand that it's possible to realise it using customized TableSelection. If any cleaner or easier workarounds are applicable I'd be grateful to have a sandbox for them.

**Comment by LazyLahtak** [comment]
Hi @zdzarsky,

Thank you for your interest in our React Grid.

We have no built-in property to choose singe selection mode. However, you can use selection in controlled mode to achieve this.
To hide checkboxes like in DataGrid, define TableSelection's `cellComponent` [property](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-selection/#properties) with a custom component. This way, you can render [TableSelection.Cell](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-selection/#tableselectioncellprops) if you selected at least one item or hovered the mouse over a cell. Otherwise, you can render [Table.Cell](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/#tablecellprops).
Here is an [example](https://codesandbox.io/s/angry-curie-o5udf?file=/demo.js).

If you have further questions, feel free to contact us.

**Comment by zdzarsky** [comment]
Thank you! I'd also suggest to use your template cell and toggle styles in checkbox to achieve the best performance :)
