### ISSUE TITLE
Material UI table / Editing cell

### ISSUE THREAD

**Issue by geoffreyLB** [DevExpress/devextreme-reactive#362]
Hi Guys, 

Wondering if you have already implement specific editing cell in the edit mode ? I can't figured out yet.

For exemple, I just wan't to edit column 'name' & 'city' but not the others. Is that possible with React ? 

Thanks

**Comment by SergeyAlexeev** [comment]
Hi,

To implement your scenario you can use the `editCellTemplate` property of the [TableEditRow](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-edit-row/) plugin. 

See the following code:

```js
<TableEditRow
  editCellTemplate={({ column, value }) => {
    if (column.name !== 'name' && column.name !== 'city') {
      return (<TableCell>{value}</TableCell>);
    }
    return undefined;
  }}
/>
```

Here I render a cell without an editor if a column name doesn't equal 'name' and 'city'. Otherwise, I use the default edit cell template.

**Comment by bloomdido** [comment]
@SergeyAlexeev - How are you accessing the `<TableCell/>` component in the code above? I appears to be located in `/packages/dx-react-grid-material-ui/src/templates/table-cell.jsx`, but I can't find it being exported anywhere.

**Comment by SergeyAlexeev** [comment]
`<TableCell/>` is  Material UI [component](https://material-ui-1dab0.firebaseapp.com/api/table-cell/). 

You can access it using this code:

```js
import { TableCell } from 'material-ui';
```

**Comment by bloomdido** [comment]
Yes, but that it won't match the `TableCell` found in [templates](https://github.com/DevExpress/devextreme-reactive/blob/v1.0.0-alpha.10/packages/dx-react-grid-material-ui/src/templates/table-cell.jsx), which overrides some styling and supports the `column.align` property. In order to use the stock material-ui `TableCell`, you will have clone the same changes.

Sounds like this is just not supported at this time. Should I open a feature request to allow exporting the templates so they can be used without having to clone their code?

**Comment by SergeyAlexeev** [comment]
Thank you for the additional information. I've created a separate [issue](https://github.com/DevExpress/devextreme-reactive/issues/368).

**Comment by geoffreyLB** [comment]
It work like a charm in my side. 

thanks you !
