### ISSUE TITLE
Scheduler not fitting parent container

### ISSUE THREAD

**Issue by tippfelher** [DevExpress/devextreme-reactive#3655]
### Is there an existing issue for this?

- [X] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### I'm using ...

React Scheduler

### Current Behaviour

According to the [docs](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/scheduler/):

<html>
<body>

height | number \| auto | auto | The scheduler's height. If the value is auto, the height equals that of the container component.
-- | -- | -- | --

</body>
</html>

But this doesn't work on any of your codesandboxes provided !?

How to make Scheduler fit the parent container?

### Expected Behaviour

Scheduler has same height as red box in sandbox. (link below)

### Steps to Reproduce

https://codesandbox.io/s/rough-water-vkdyql?file=/demo.js

### Environment

- devextreme-reactive: xxx
- react: xxx
- browser: xxx
- bootstrap: none
- react-bootstrap: none
- material-ui: none

**Comment by Madobyte** [comment]
Hello @tippfelher,

If you inspect the scheduler element, you will see that `height='auto'` works correctly because the scheduler element has a height of `100%`. However, if you wish to make the scheduler responsive to its parent container's height, you need to implement [WeekView.TimeTableCell](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/week-view/#weekviewtimetablecellprops) and [WeekView.TimeScaleLayout](https://devexpress.github.io/devextreme-reactive/react/scheduler/docs/reference/week-view/#weekviewtimescalelayoutprops) and manually define each cell's height.

I created a sample to demonstrate this solution: [CodeSandbox](https://codesandbox.io/s/naughty-wood-khyymh?file=/demo.js).

A similar solution was described in the following report: [Responsive Scheduler MonthView Height #2706
](https://github.com/DevExpress/devextreme-reactive/issues/2706).

Let me know if you have additional questions.
