### ISSUE TITLE
A easier way to portal suggestions' list ? 

### ISSUE THREAD

**Issue by be-next-hotdog** [DevExpress/devextreme-reactive#418]
Yopp to all,

I added several dynamic search field (basis of React-suggestions/ MUI autocomplete )in the TableCell and the scope of TableCell captures the suggestions' list. So I would like to ask if you've a better way to make it display normally or just portal this `list dom` ?

Here's a screen capture : 
<img width="251" alt="example" src="https://user-images.githubusercontent.com/10281179/31676207-2d7863a2-b367-11e7-9af4-4434e79776e5.png">

Thx for any helpful tips ;)

**Comment by SergeyAlexeev** [comment]
Hello,

The Material UI adds the `overflow: hidden` CSS property for the `table` tag. Due to this reason, the suggestion list in your sample is cropped. I suggest you put a custom autocomplete control outside a table. 
Please refer to [the thread](https://github.com/moroshko/react-autosuggest/issues/308) where a similar issue was discussed. A possible solution is described [here](https://github.com/moroshko/react-autosuggest/issues/258).

**Comment by kvet** [comment]
Hi,

We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
