### ISSUE TITLE
Table doesn't get rerender when the table data is managed by mobx, and data changed by other react component(form)

### ISSUE THREAD

**Issue by geohuz** [DevExpress/devextreme-reactive#452]
I have noticed that the data in the table changed after clicking on other page then switching back. The original material-ui table component doesn't have this issue. The code is like:

```
const PersonsTable = observer((props) => { 
    <Grid rows={data} columns...>
       ....
    </Grid>
```
observer is a highorder component which will trigger the component rerender when the managed state (data) is changed. I have another component which is a form share the same data with table. If I change the data in the form , the table doesn't get rerender only after changing page then switch back.

I have done the test for the original material-ui table and it gets rerender immediately.

**Comment by kvet** [comment]
Hi,
 
We use PureComponent instead of Component as a general performance optimization technique. React Grid will not be rendered when data is mutated. As a workaround, I can recommend creating a new instance of arrays and objects when nested data is mutated.

**Comment by geohuz** [comment]
@kvet May you elaborate the idea a little bit more? Thanks!

**Comment by kvet** [comment]
Unfortunately, I don't have an example implementing my idea. But you can try to implement it yourself. It seems that React Grid is not the only library that has integration problems with Mobx and it may be possible to find a solution on StackOverflow, for example.

**Comment by kvet** [comment]
I researched the issue and found a solution.
 
The main problem with a seamless integration with MobX is that React Grid uses immutable data as a general performance optimization technique. And it is suitable for React because it has PureComponent for performing updates only when data is changed. It is also true for Redux. MobX is opposite to them. It encourages data mutations in observables and performs updates once underlying data is changed. So, both immutable data and data mutations in observables tend to improve performance. And the easiest way to integrate React Grid into an application with MobX is to convert you mutable data to immutable. It can be done with the `createTransformer` utility function designed for MobX. Here is an example: https://stackblitz.com/edit/react-wtf3rj?file=index.js
 
Feel free to contact us if you need further assistance.
