### ISSUE TITLE
Material-ui ways error

### ISSUE THREAD

**Issue by mathetes** [DevExpress/devextreme-reactive#592]
I have such problem with links to material-ui modules.

ERROR in ./~/@devexpress/dx-react-grid-material-ui/dist/dx-react-grid-material-ui.cjs.js
Module not found: Error: Cannot resolve module 'material-ui/Input'

**Comment by MaximKudriavtsev** [comment]
Hi,
seems like you include another `material-ui` package to your project.
Remove the current `material-ui` package from your project and try `material-ui: 1.0.0-beta.23`
`npm install --save material-ui@1.0.0-beta.23`

If this does not resolve your problem, please, contact us again providing more information about your environment.

**Comment by MaximKudriavtsev** [comment]
Hi,
seems like you include another `material-ui` package to your project.
Remove the current `material-ui` package from your project and try `material-ui: 1.0.0-beta.23`
`npm install --save material-ui@1.0.0-beta.23`
 
If this does not resolve the problem, please, contact us again providing more information about your environment.

**Comment by Phocea** [comment]
Our current project is using material-ui 0.9. We have not migrated to 1.0 yet since there s a lot of BC change to do first.
Will devextreme react grid work with 0.9 ?

**Comment by SergeyAlexeev** [comment]
No, our React Grid works with Material UI v.1.0.0*

**Comment by Phocea** [comment]
So how can we make this work alongside another version. We are currently evaluating your product prior to buy commercial licences, but this dependency simple stop us right there....

**Comment by SergeyAlexeev** [comment]
We appreciate your interest in our product.  Currently, we haven't found a good solution for this case. The problem is that both (old and new) libraries cannot be used in the same project because they have the same component names, etc. At the same time, the implementation is completely different and thus, the previous version is not compatible with our Grid. If you're interested in using our grid in your application, consider upgrading Material UI to be able to use it.

**Comment by kvet** [comment]
We are closing the issue due to inactivity. Feel free to reopen it if you need further assistance.
