### ISSUE TITLE
[Question] Table.Cell or TableCell from material-ui

### ISSUE THREAD

**Issue by timothyvanderaerden** [DevExpress/devextreme-reactive#608]
Hello

Considering the following example (only the important pieces):
```
import { Grid, Table } from '@devexpress/dx-react-grid-material-ui';
import { TableCell  } from 'material-ui/Table';

...

cellComponent = (props) => {
    if (props.column.name === 'action') {
      return (
        <TableCell>
              <IconButton aria-label="Edit">
                <EditIcon/>
              </IconButton>
        </TableCell>
      );
    }
    return <Table.Cell {...props} />;
  };

...

 <Grid
    rows={props.data}
    columns={props.columns}
>
    <Table cellComponent={this.cellComponent}/>
</Grid>
```

Throughout the docs/demos `TableCell` is used in such cases, but wouldn't `Table.Cell` suffice instead of using an extra import from material-ui? Like:
```
import { Grid, Table } from '@devexpress/dx-react-grid-material-ui';

...

cellComponent = (props) => {
    if (props.column.name === 'action') {
      return (
        <Table.Cell>
              <IconButton aria-label="Edit">
                <EditIcon/>
              </IconButton>
        </Table.Cell>
      );
    }
    return <Table.Cell {...props} />;
  };
```
It just seems like an unneeded import because `Table.Cell` already inherits from TableCell. Or Am I in the wrong?

devextreme-reactive: 1.0.0-beta.2
material-ui: 1.0.0-beta.24

**Comment by kvet** [comment]
Hi,
 
The use of the TableCell or Table.Cell components depend on your needs.
 
As a general advice, we expect using the Table.Cell component for simple customizations. For example, if you need to add an additional event listener, or slightly change styling. Otherwise, consider using the TableCell component as it will give you more flexibility.
 
The same rule can be applied to other plugins and other plugin components.

**Comment by timothyvanderaerden** [comment]
Hello

Thank you for the clarification. In my example Table.Cell would suffice, but I can imagine the use of TableCell.
