### ISSUE TITLE
Row detail with height greater than Virtual Table height breaks row layout

### ISSUE THREAD

**Issue by stclairdaniel** [DevExpress/devextreme-reactive#745]
- [x ] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
When a row detail's height is greater than the Virtual Table's height, scrolling in the detail breaks the <tr> layout. See GIF:
![feb-14-2018 09-56-21](https://user-images.githubusercontent.com/14972752/36219938-d70dcb1e-116d-11e8-8d6c-9abb9dba361a.gif)

### Expected Behaviour
Row detail should be allowed arbitrary height and scrolling should be smooth

### Steps to Reproduce (for Bugs)

Create a Virtual Table with any specified height and create a row with row detail with height greater than specified height. Scroll in row detail.

devextreme-reactive: xxx
react: 1.0.0-rc.1
browser: Chroms latest release
bootstrap: none
react-bootstrap: none
material-ui: 1.0.0-beta.30

**Comment by freund17** [comment]
I'm experiencing the same issue.
I also first noticed it when using RowDetail.
It is - however - not limited to that.
This kind of flicker always happens when the usable height in the virtual table is smaller than 2 rows worth of height. So this behaviour can as well be reproduced by using a small VirtualTable. (No RowDetails required)

An other detail you might miss in the gif: when continuing scrolling, the rows reappear.
There seems to be a small area (~5 px), just when the top edge of the first row scrolls off screen while the bottom edge of the second row is still off screen, where the rows disappear. Scrolled past this point (either the bottom edge of the second row enters the screen OR the second row becomes the only row on screen) the row(s) reappear.

I suspect the error to be somewhere in https://github.com/DevExpress/devextreme-reactive/blob/master/packages/dx-react-grid/src/components/table-layout/virtual-table-layout.jsx

**Comment by freund17** [comment]
So the behaviour can be summarized as:

When there are exactly 2 rows visible AND
the top edge of the first row is off screen AND
the bottom edge of the second row is off screen
the rows are hidden.

Otherwise the rows are shown as expected.

**Comment by kvet** [comment]
Hi,
 
The fix is available in the 1.0.1 release.
