### ISSUE TITLE
Hover Row Responsiveness

### ISSUE THREAD

**Issue by slane2016** [DevExpress/devextreme-reactive#757]
Is ther any plans to make the rows responsive on hover such as: https://react-table.js.org/#/story/simple-table.

**Comment by SergeyAlexeev** [comment]
Hi,
 
To implement this scenario override the `rowComponent` property of the [Table](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table/) plugin.
 
This [sample](https://codesandbox.io/s/rylk1x324o) shows how to do it. Here I apply a custom CSS class to the default `Table.Row` component:

```js
const styles = {
  customRow: {
    '&:hover': {
      backgroundColor: 'lightgray',
    }
  },
};

const CustomTableRowBase = ({ classes, ...restProps }) => (
  <Table.Row
    className={classes.customRow}
    {...restProps}
  />
);
```

Note, I am using the Material UI in my sample.

**Comment by SerhiiBilyk** [comment]
`  <Grid rows={rows} columns={columns} getRowId={getRowId}>
            <Table cellComponent={Cell} rowComponent={CustomTableRowBase} />
            <TableHeaderRow />
          </Grid>`

`const CustomTableRowBase = ({ classes, ...restProps }) => (
  <Table.Row
    className={{
      '&:hover': {
        backgroundColor: 'lightgray',
      },
    }}
    {...restProps}
  />
);`
React throws an error : warning.js?da67:33 Warning: Encountered two children with the same key, `data_enter`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.

How to implement row id?
