### ISSUE TITLE
How to keep focus on input change?

### ISSUE THREAD

**Issue by andrispraulitis** [DevExpress/devextreme-reactive#771]
Question

Hi, I want to render an input field in table cell (editing functionality not an option in this case) and I also need to pass onChange function to cell component, but by doing that input field always looses focus after re-render. Any way to fix that?

Example (will keep focus)
`<Table cellComponent={RowCell} />`

Example (will loose focus)
`<Table cellComponent={props => <RowCell myProp={onChange} {...props}/>} />`

Note: This example also happens on filtering not just table cells.

**Comment by SergeyAlexeev** [comment]
Hi,
 
As far as I understand, the main problem you faced is updating rows when an input value is changed:
```js
  this.setState({ rows: updatedRows });
```
If so, I'd suggest you use a state management library, like [Redux](https://redux.js.org/) to update rows. We have a [guide](https://devexpress.github.io/devextreme-reactive/react/grid/docs/guides/immutable-data/) that shows how to use React Grid and Redux together.
 
In case you want to update the state without Redux, you can use the approach from this [sample](https://codesandbox.io/s/0p20yjwj5l).

**Comment by andrispraulitis** [comment]
Hi @SergeyAlexeev 

Thanks, I finally got this working.

**Comment by elmeerr** [comment]
Hi, I came across this issue because I'm facing the same situation and I didn't really understand how to solve. I want a textfield that display inline validations when it has errors. The first step is to render this textfield as DataTypeProvider so far so good, but when I call the onChange method, it loses focus why?

TextField:
```
   <TextField
                name={name}
                value={value}
                onChange={e => onValueChange(e.target.value)}
            />
```

Provider:

`
const InputValidationTypeProvider = props => {
    const textFieldComponent = prop => <TextFieldCell {...prop} name={prop.column.name} />
    return <DataTypeProvider editorComponent={textFieldComponent} for={props.for} />
}

`

update on added changes: 

```
   handleAddedRowsChanges = addedRowsChanges => {
        this.setState({ addedRows: [...addedRowsChanges] })
    }
```

I don't really understand why is losing the focus (beside the facts it's rerendering)...what am I missing?

p.s.: I think you could have more information docs regarding Customization

Thanks in advance

**Comment by QuantumInformation** [comment]
@andrispraulitis how did you fix it?

We have the following `          <FilteringState filters={filters} onFiltersChange={this.changeFilters} />
`
and always lose focus, we were just coping the controlled example

**Comment by QuantumInformation** [comment]
Shall I open a new issue for this?

**Comment by andrispraulitis** [comment]
Not sure, this was long time ago...
