### ISSUE TITLE
Override TableSelection Checkbox

### ISSUE THREAD

**Issue by joergd** [DevExpress/devextreme-reactive#933]
I want to override the colour used on the TableSelection Checkbox (using material). I couldn't find any way to pass classes to the checkbox used which would have been easiest.

So I had to resort to overriding the cellComponent used for the TableSelection, but I think there is a bug - my custom component is never used.

    const TableSelectionComponent = ({ row, selected, onToggle, children }) => {
      return (
        <TableSelection.Cell
           row={row}
           onToggle={onToggle}
           selected={selected}
        >
          <Checkbox
            className={classes.checkbox}
            classes={ { checked: classes.checked }}
            checked={selected}
            onClick={(e) => {
              e.stopPropagation();
              onToggle();
            }}
          />
        </TableSelection.Cell>
      )
    }

And, in the Grid I use

    <TableSelection cellComponent={TableSelectionComponent} showSelectAll />

I'm using v1.1.2

**Comment by SergeyAlexeev** [comment]
Hi,

As you can see in the [documentation](https://devexpress.github.io/devextreme-reactive/react/grid/docs/reference/table-selection#tableselectioncellprops), the `TableSelection.Cell` component doesn't contain the `children` property. That's why your sample doesn't work as you expect.

Anyway, I should say your idea seems useful, we will discuss the possibility of supporting the scenario you described in the future.

For now, I suggest you use the [MuiThemeProvider](https://material-ui-1dab0.firebaseapp.com/api/mui-theme-provider/#muithemeprovider) component to change a checkbox color.
This [sample](https://stackblitz.com/edit/react-4b56pu?file=index.js) shows how it can be implemented.

**Comment by joergd** [comment]
Hi Sergey,

Ok cool - yes that workaround is better than overriding the whole component - thank you.

**Comment by AryamnovEugeniy** [comment]
Updated example. Overriding color in CheckBox.
https://codesandbox.io/s/devextreme-react-grid-for-material-ui-smhnq?fontsize=14
