### ISSUE TITLE
Specific Material-ui version is required

### ISSUE THREAD

**Issue by hannav95** [DevExpress/devextreme-reactive#952]
- [x] I have searched this repository's [issues](https://github.com/devexpress/devextreme-reactive/issues) and believe that this is not a duplicate.

### Current Behaviour
In order to have build properly on Cloud Foundry, we have to require the specific version (`material-ui@1.0.0-beta.41`)

### Expected Behaviour
Should be able to have current material-ui version for peer dependency

### Steps to Reproduce (for Bugs)

npm install during build with `"material-ui": "^1.0.0-beta.42"` in package.json

### Your Environment

devextreme-reactive: 1.1.2
react: 16.3.2
browser: Chrome v63
bootstrap: none
react-bootstrap: none
material-ui: none

**Comment by kvet** [comment]
Hi,

Currently, the `material-ui@1` library is not stable. We don't specify a range of supported versions due to this reason. We use a specific version to say that this version is tested and we know that it works well with React Grid.

The version specified in peer dependencies doesn't mean that we support only this specific version. You can update the `material-ui` package version and use it. However, you will do it at your own risk.

**Comment by hannav95** [comment]
Whenever I do not specify the current version you have in peer dependency, I get the following error during the build
![image](https://user-images.githubusercontent.com/12763767/38936981-1347d1f2-42f0-11e8-9971-3010b6a0d3cf.png)

**Comment by kvet** [comment]
Typically, npm only warns about unmet peer dependencies. Maybe you are using an old npm version or specially configured it to throw an error? Here is my command output:


```
test-npm% npm i
npm WARN @devexpress/dx-react-grid-material-ui@1.1.2 requires a peer of material-ui@1.0.0-beta.41 but none is installed. You must install peer dependencies yourself.

up to date in 0.595s
```

**Comment by hannav95** [comment]
You're correct. I had to specify a more current version of node for the build pack to use & I am not facing this issue anymore. Thank you for your help!
